(()=>{const LX=window.LX,D=LX.data,S=LX.store,U=LX.ui,$=U.$,$$=U.$$ ,esc=U.esc;
const head=(t,p)=>`<div class="admin-head"><div><span class="eyebrow">LX ADMIN · v18</span><h1>${t}</h1><p>${p}</p></div></div>`;
function render(page='dashboard'){U.state.adminPage=page;const m=$('adminMain');({dashboard,library,quality,uploads,requests,community,premium,analytics,notifications,settings}[page]||dashboard)(m);bind(page)}
function dashboard(m){const c=D.catalog(),u=D.users(),req=D.requests(),bad=c.filter(x=>D.quality(x).score<100);m.innerHTML=head('Visão geral','Catálogo, qualidade, comunidade e sinais de operação em um único painel.')+`<div class="admin-quick-add"><div><span class="eyebrow">PUBLICAR AGORA</span><strong>Adicionar conteúdo</strong><small>Abra o formulário certo com um clique.</small></div><div class="quick-add-actions">${['Filme','Série','Anime','Dorama','Livro','Música'].map(t=>`<button onclick="LX.admin.edit(null,'${t}')"><span>${t==='Filme'?'🎬':t==='Série'?'▣':t==='Anime'?'✦':t==='Dorama'?'♡':t==='Livro'?'▤':'♫'}</span>${t}</button>`).join('')}</div></div><div class="stats"><div class="stat"><small>CONTEÚDOS</small><strong>${c.length}</strong></div><div class="stat"><small>USUÁRIOS</small><strong>${u.length}</strong></div><div class="stat"><small>PENDÊNCIAS DE QUALIDADE</small><strong>${bad.length}</strong></div><div class="stat"><small>PEDIDOS ABERTOS</small><strong>${req.filter(x=>!['Concluído','Fechado'].includes(x.status)).length}</strong></div></div><div class="admin-grid"><div class="admin-card"><h2>Atividade simulada — 14 períodos</h2><div class="chart">${[38,62,51,79,58,92,73,88,65,96,82,105,91,118].map(h=>`<i style="height:${h}px"></i>`).join('')}</div></div><div class="admin-card"><h2>Saúde da plataforma</h2><div class="health-grid"><div class="health-card"><span class="status">Frontend</span><strong>Operacional</strong><small>PWA e cache local ativos</small></div><div class="health-card"><span class="status ${LX.config.production?'':'warn'}">Backend</span><strong>${LX.config.production?'Conectado':'Modo local'}</strong><small>${LX.config.production?'API configurada':'Conectar API para produção'}</small></div><div class="health-card"><span class="status warn">Streaming</span><strong>Interface pronta</strong><small>HLS depende do pipeline de mídia</small></div><div class="health-card"><span class="status">Qualidade</span><strong>${Math.round(c.reduce((a,x)=>a+D.quality(x).score,0)/c.length)}%</strong><small>Média do catálogo</small></div></div></div></div>`}
function library(m){const c=D.catalog(),types=['Filme','Série','Anime','Dorama','Livro','Música'],t=U.state.libraryType||'Todos';m.innerHTML=head('Biblioteca','Cada mídia tem seu fluxo próprio, sem misturar episódios, faixas e capítulos.')+`<div class="library-summary">${types.map(x=>`<button data-libsummary="${x}" class="${t===x?'active':''}"><small>${x==='Música'?'Música':x+'s'}</small><strong>${c.filter(z=>z.type===x).length}</strong></button>`).join('')}</div><div class="admin-card"><div class="library-tabs"><button data-lib="Todos" class="${t==='Todos'?'active':''}">Tudo</button>${types.map(x=>`<button data-lib="${x}" class="${t===x?'active':''}">${x==='Música'?'Música':x+'s'}</button>`).join('')}</div><div class="admin-toolbar"><input id="libSearch" placeholder="Buscar nesta biblioteca"><select id="libStatus"><option>Todos os status</option><option>Publicado</option><option>Rascunho</option></select><button id="newContent" class="primary-btn">＋ Novo conteúdo</button></div><div style="overflow:auto"><table class="admin-table"><thead><tr><th>Título</th><th>Tipo</th><th>Estrutura</th><th>Qualidade</th><th>Status</th><th>Ações</th></tr></thead><tbody id="libRows">${rows(c)}</tbody></table></div></div>`}
function rows(a){return a.map(x=>{const q=D.quality(x);const structure=x.type==='Livro'?`${x.chapters?.length||0} capítulos`:x.type==='Música'?`${x.tracks?.length||0} faixas`:['Série','Anime','Dorama'].includes(x.type)?`${x.episodes?.length||0} episódios`:'1 título';return `<tr><td><b>${esc(x.title)}</b><br><small style="color:var(--muted)">${esc(x.genre)}</small></td><td>${esc(x.type)}</td><td>${structure}</td><td><span class="quality-score ${q.score<100?'warn':''}">${q.score}%</span></td><td>${x.published===false?'Rascunho':'Publicado'}</td><td><button onclick="LX.admin.edit(${x.id})">Editar</button> <button onclick="LX.admin.del(${x.id})">Excluir</button></td></tr>`}).join('')}
function quality(m){const a=D.catalog().map(x=>({x,q:D.quality(x)})).sort((a,b)=>a.q.score-b.q.score);m.innerHTML=head('Controle de qualidade','Antes de publicar, a LX verifica os campos essenciais de cada tipo de mídia.')+`<div class="admin-card"><div class="quality-list">${a.map(({x,q})=>`<div class="quality-row"><div><strong>${esc(x.title)} · ${esc(x.type)}</strong><small>${q.checks.filter(c=>!c.ok).length?q.checks.filter(c=>!c.ok).map(c=>c.label).join(' · '):'Pronto para publicação'}</small></div><span class="quality-score ${q.score<100?'warn':''}">${q.score}%</span></div>`).join('')}</div></div>`}
function uploads(m){
 const epWorks=D.catalog().filter(x=>['Série','Anime','Dorama'].includes(x.type));
 const musicWorks=D.catalog().filter(x=>x.type==='Música');
 m.innerHTML=head('Mídia & Upload','Uploads em lote agora são separados por estrutura: episódios de um lado, faixas de música do outro.')+`
 <div class="admin-card">
  <div class="upload-mode-tabs">
   <button class="active" data-uploadmode="episodes">▶ Episódios</button>
   <button data-uploadmode="tracks">♫ Faixas de música</button>
  </div>
  <div id="uploadModeBody"></div>
  <div id="dropzone" class="dropzone" style="margin-top:12px"><div><h3 id="dropTitle">Arraste os episódios aqui</h3><p id="dropHelp">Detecta E01 / EP02 automaticamente.</p><button id="chooseBatch" class="primary-btn">Selecionar arquivos</button><input id="batchFiles" type="file" multiple accept="video/*"></div></div>
  <div id="uploadQueue" class="upload-queue"></div><button id="processBatch" class="primary-btn" style="margin-top:12px">Processar lote</button>
 </div>`;
 U.state.uploadMode='episodes';
 const body=$('uploadModeBody');
 const drawMode=()=>{
  const tracks=U.state.uploadMode==='tracks';
  body.innerHTML=tracks?`<div class="form-grid"><label class="field">Artista / álbum<select id="batchContent">${musicWorks.map(x=>`<option value="${x.id}">${esc(x.title)} · ${esc(x.artist||'Artista')}</option>`).join('')}</select></label><label class="field">Numeração inicial<input id="batchStart" type="number" min="1" value="1"></label></div><div class="media-form-note"><b>Faixas</b><span>Áudio apenas. O banner não participa do cadastro de música; capa e metadados ficam na obra.</span></div>`:`<div class="form-grid"><label class="field">Série / anime / dorama<select id="batchContent">${epWorks.map(x=>`<option value="${x.id}">${esc(x.title)} · ${x.type}</option>`).join('')}</select></label><label class="field">Temporada<input id="batchSeason" type="number" min="1" value="1"></label></div><div class="media-form-note"><b>Episódios</b><span>Vídeos separados por temporada. Use E01, E02, EP03 no nome para ordenar automaticamente.</span></div>`;
  $('batchFiles').accept=tracks?'audio/*':'video/*';$('dropTitle').textContent=tracks?'Arraste as músicas aqui':'Arraste os episódios aqui';$('dropHelp').textContent=tracks?'MP3, M4A, AAC, WAV ou outros formatos aceitos pelo navegador.':'Detecta E01 / EP02 automaticamente.';
 };
 drawMode();
 $$('[data-uploadmode]').forEach(b=>b.onclick=()=>{U.state.uploadMode=b.dataset.uploadmode;$$('[data-uploadmode]').forEach(x=>x.classList.toggle('active',x===b));drawMode();$('uploadQueue').innerHTML='';$('batchFiles').value=''});
}
function requests(m){const r=D.requests().sort((a,b)=>(b.votes||1)-(a.votes||1)||b.created-a.created);m.innerHTML=head('Pedidos & Problemas','Pedidos repetidos são agrupados e ganham votos, ajudando a priorizar o catálogo.')+`<div class="stats"><div class="stat"><small>TOTAL</small><strong>${r.length}</strong></div><div class="stat"><small>NOVOS</small><strong>${r.filter(x=>x.status==='Novo').length}</strong></div><div class="stat"><small>EM ANÁLISE</small><strong>${r.filter(x=>x.status==='Em análise').length}</strong></div><div class="stat"><small>CONCLUÍDOS</small><strong>${r.filter(x=>x.status==='Concluído').length}</strong></div></div><div class="request-grid" style="margin-top:12px">${r.length?r.map(x=>`<article class="request-card"><strong>${esc(x.title)}</strong><small>${esc(x.kind)} · ${esc(x.mediaType)} · ${esc(x.userName)}</small><p>${esc(x.message)}</p><div class="request-badges"><span>${esc(x.status)}</span><span class="vote-pill">▲ ${x.votes||1} pedidos</span></div><div class="request-actions"><button onclick="LX.admin.reqStatus(${x.id},'Em análise')">Analisar</button><button onclick="LX.admin.reqStatus(${x.id},'Concluído')">Concluir</button><button onclick="LX.admin.reqStatus(${x.id},'Fechado')">Fechar</button></div></article>`).join(''):'<div class="request-card">Nenhuma solicitação recebida.</div>'}</div>`}
function community(m){const u=D.users();m.innerHTML=head('Comunidade','Verificação, privacidade e sinais de engajamento.')+`<div class="admin-card" style="overflow:auto"><table class="admin-table"><thead><tr><th>Usuário</th><th>Assistiu</th><th>Ouviu</th><th>Leu</th><th>Ranking</th><th>Verificação</th></tr></thead><tbody>${u.map(x=>`<tr><td><b>${LX.verified(x.name,x.verified)}</b><br><small style="color:var(--muted)">${esc(x.email)}</small></td><td>${Math.round(x.watched||0)}h</td><td>${Math.round(x.listened||0)}h</td><td>${x.read||0}</td><td>${x.visible===false?'Oculto':'Ativo'}</td><td><button onclick="LX.admin.verify(${x.id})">${x.verified?'Remover':'Verificar'}</button></td></tr>`).join('')}</tbody></table></div>`}
function premium(m){const users=D.users(),subs=D.subscriptions(),active=Object.values(subs).filter(x=>x?.active).length,monthly=Object.values(subs).filter(x=>x?.active&&x.plan==='Mensal').length,annual=Object.values(subs).filter(x=>x?.active&&x.plan==='Anual').length;m.innerHTML=head('Premium','Gerencie assinaturas no protótipo. Em produção, o status deve vir exclusivamente do backend e do provedor de pagamento.')+`<div class="stats"><div class="stat"><small>PREMIUM ATIVOS</small><strong>${active}</strong></div><div class="stat"><small>MENSAIS</small><strong>${monthly}</strong></div><div class="stat"><small>ANUAIS</small><strong>${annual}</strong></div><div class="stat"><small>USUÁRIOS</small><strong>${users.length}</strong></div></div><div class="admin-card" style="margin-top:12px;overflow:auto"><table class="admin-table"><thead><tr><th>Usuário</th><th>Plano</th><th>Status</th><th>Validade</th><th>Ações demo</th></tr></thead><tbody>${users.map(u=>{const x=subs[u.email],enc=encodeURIComponent(u.email);return `<tr><td><b>${esc(u.name)}</b><br><small style="color:var(--muted)">${esc(u.email)}</small></td><td>${x?.active?`<span class="premium-user-pill">${esc(x.plan||'Premium')}</span>`:'Free'}</td><td>${x?.active?'Ativo':'Inativo'}</td><td>${x?.until?new Date(x.until).toLocaleDateString('pt-BR'):'—'}</td><td><div class="admin-premium-actions"><button onclick="LX.admin.premiumSet(decodeURIComponent('${enc}'),'Mensal')">Mensal</button><button onclick="LX.admin.premiumSet(decodeURIComponent('${enc}'),'Anual')">Anual</button>${x?.active?`<button onclick="LX.admin.premiumOff(decodeURIComponent('${enc}'))">Desativar</button>`:''}</div></td></tr>`}).join('')}</tbody></table></div><div class="admin-card" style="margin-top:12px"><h2>Produção</h2><p style="color:var(--muted);line-height:1.6">Ações desta tela são somente de demonstração. No site público, assinatura deve ser criada pelo checkout, confirmada no backend por webhook e nunca liberada apenas pelo JavaScript do navegador.</p></div>`}
function analytics(m){const a=D.analytics(),counts={};a.forEach(x=>counts[x.event]=(counts[x.event]||0)+1);const searches=a.filter(x=>x.event==='search').map(x=>x.data.query).filter(Boolean),opens=a.filter(x=>x.event==='open').map(x=>x.data.title).filter(Boolean);const top=arr=>Object.entries(arr.reduce((o,x)=>(o[x]=(o[x]||0)+1,o),{})).sort((a,b)=>b[1]-a[1]).slice(0,8);m.innerHTML=head('Analytics','Eventos locais no protótipo; em produção, envie os mesmos eventos para o backend.')+`<div class="stats"><div class="stat"><small>EVENTOS</small><strong>${a.length}</strong></div><div class="stat"><small>ABERTURAS</small><strong>${counts.open||0}</strong></div><div class="stat"><small>BUSCAS</small><strong>${counts.search||0}</strong></div><div class="stat"><small>PLAY/LEITURA</small><strong>${(counts.play||0)+(counts.read||0)+(counts.music||0)}</strong></div></div><div class="admin-grid"><div class="admin-card"><h2>Conteúdos mais abertos</h2>${top(opens).map(([x,n],i)=>`<div class="rank-row"><span class="position">#${i+1}</span><strong>${esc(x)}</strong><b>${n}</b></div>`).join('')||'<p style="color:var(--muted)">Abra alguns conteúdos para gerar dados.</p>'}</div><div class="admin-card"><h2>Buscas frequentes</h2>${top(searches).map(([x,n])=>`<div class="rank-row"><span>⌕</span><strong>${esc(x)}</strong><b>${n}</b></div>`).join('')||'<p style="color:var(--muted)">Ainda não há buscas.</p>'}</div></div>`}
function notifications(m){m.innerHTML=head('Notificações','Publique avisos internos. Push real entra quando o backend estiver online.')+`<div class="admin-card"><div class="form-grid"><label class="field">Título<input id="noticeTitle"></label><label class="field">Tempo exibido<input id="noticeTime" value="Agora"></label><label class="field span2">Mensagem<textarea id="noticeText" rows="4"></textarea></label></div><button id="sendNotice" class="primary-btn" style="margin-top:12px">Publicar notificação</button></div>`}
function settings(m){m.innerHTML=head('Produção','Arquitetura pronta para trocar armazenamento local por API, banco, storage e CDN.')+`<div class="admin-grid"><div class="admin-card"><h2>Ambiente</h2><div class="health-grid"><div class="health-card"><span class="status ${LX.config.production?'':'warn'}">API</span><strong>${LX.config.production?'Produção':'Local'}</strong><small>${LX.config.apiBase||'backend não configurado'}</small></div><div class="health-card"><span class="status warn">Storage/CDN</span><strong>Adaptador preparado</strong><small>Configure provider no backend</small></div><div class="health-card"><span class="status warn">HLS</span><strong>Pipeline definido</strong><small>Transcodificação requer worker/FFmpeg</small></div><div class="health-card"><span class="status">PWA</span><strong>Ativo</strong><small>Service Worker incluso</small></div></div></div><div class="admin-card"><h2>Segurança</h2><p style="color:var(--muted)">No modo produção: senha nunca fica no frontend, sessões usam cookies HttpOnly/Secure, rate limiting, RBAC e logs administrativos.</p><p><code>backend/.env.example</code></p><p><code>backend/sql/schema.sql</code></p><p><code>docs/SECURITY.md</code></p></div></div>`}
function bind(page){
 if(page==='library'){
  const apply=()=>{const q=$('libSearch').value.toLowerCase(),s=$('libStatus').value,t=U.state.libraryType;const a=D.catalog().filter(x=>(t==='Todos'||x.type===t)&&(!q||D.normalize([x.title,x.genre,x.type,x.artist,x.author,x.director,x.creator,x.studio].join(' ')).includes(D.normalize(q)))&&(s==='Todos os status'||(s==='Publicado'?x.published!==false:x.published===false)));$('libRows').innerHTML=rows(a)};
  $$('[data-lib]').forEach(b=>b.onclick=()=>{U.state.libraryType=b.dataset.lib;render('library')});$$('[data-libsummary]').forEach(b=>b.onclick=()=>{U.state.libraryType=b.dataset.libsummary;render('library')});$('libSearch').oninput=apply;$('libStatus').onchange=apply;$('newContent').onclick=()=>edit(null,U.state.libraryType==='Todos'?'Filme':U.state.libraryType)
 }
 if(page==='uploads'){
  let files=[];const inp=$('batchFiles'),zone=$('dropzone');
  const draw=()=>{$('uploadQueue').innerHTML=files.map((f,i)=>`<div class="upload-item"><div><b>${esc(f.name)}</b><small>${(f.size/1024/1024).toFixed(1)} MB · ${U.state.uploadMode==='tracks'?'faixa '+(i+1):(detect(f.name)?'E'+detect(f.name):'episódio')}</small></div><span>aguardando</span></div>`).join('')};
  $('chooseBatch').onclick=()=>inp.click();inp.onchange=()=>{files=[...inp.files];draw()};['dragenter','dragover'].forEach(e=>zone.addEventListener(e,v=>{v.preventDefault();zone.classList.add('drag')}));['dragleave','drop'].forEach(e=>zone.addEventListener(e,v=>{v.preventDefault();zone.classList.remove('drag')}));zone.ondrop=e=>{files=[...e.dataTransfer.files];draw()};
  $('processBatch').onclick=async()=>{const id=+$('batchContent')?.value,a=D.catalog(),x=a.find(z=>z.id===id);if(!x||!files.length)return LX.toast('Escolha uma obra e os arquivos.');if(U.state.uploadMode==='tracks'){
    x.tracks=x.tracks||[];let n=+$('batchStart')?.value||x.tracks.length+1;for(const f of files){const key=await S.putMedia('track_'+x.id+'_'+Date.now()+'_'+f.name,f);x.tracks.push({number:n++,title:f.name.replace(/\.[^.]+$/,''),duration:0,mediaKey:key})}x.tracks.sort((a,b)=>(a.number||0)-(b.number||0));
   }else{
    x.episodes=x.episodes||[];let next=Math.max(0,...x.episodes.map(e=>e.number||0))+1;for(const f of files){const n=detect(f.name)||next++;const key=await S.putMedia(`ep_${x.id}_${n}_${Date.now()}`,f);x.episodes.push({season:+$('batchSeason').value||1,number:n,title:f.name.replace(/\.[^.]+$/,''),mediaKey:key})}x.episodes.sort((a,b)=>a.season-b.season||a.number-b.number)
   }D.saveCatalog(a);LX.toast(`${files.length} arquivos adicionados.`);render('uploads')
  }
 }
 if(page==='notifications')$('sendNotice').onclick=()=>{const t=$('noticeTitle').value.trim(),text=$('noticeText').value.trim();if(!t||!text)return LX.toast('Preencha título e mensagem.');const n=D.notices();n.unshift({id:Date.now(),title:t,text,time:$('noticeTime').value||'Agora',read:false});S.write(S.keys.notices,n);LX.toast('Notificação publicada.');render('notifications')}
}
function detect(n){const m=n.match(/(?:E|EP|episodio|episode)[ ._-]?(\d{1,3})/i);return m?+m[1]:null}
async function edit(id=null,initialType=null){
 const x=id?D.catalog().find(z=>z.id===id):null,type=x?.type||initialType||'Filme';
 $('modal').innerHTML=`<button class="close-btn" onclick="LX.ui.close()">×</button><div class="panel-page content-editor-page"><span class="eyebrow">${x?'EDITAR':'NOVO'} CONTEÚDO · v18</span><h2>${x?'Editar':'Adicionar'} conteúdo</h2><p class="editor-intro">O formulário muda conforme o tipo. Campos marcados como <b>obrigatório</b> entram no controle de qualidade antes da publicação.</p>
 <form id="contentForm" class="form-grid">
  <label class="field">Título <span class="req">obrigatório</span><input id="cTitle" required value="${esc(x?.title||'')}"></label>
  <label class="field">Tipo <span class="req">obrigatório</span><select id="cType">${['Filme','Série','Anime','Dorama','Livro','Música'].map(t=>`<option ${type===t?'selected':''}>${t}</option>`).join('')}</select></label>
  <label class="field">Ano <span class="req">obrigatório</span><input id="cYear" type="number" min="1900" max="2100" value="${x?.year||2026}"></label>
  <label class="field">Classificação <span class="req">obrigatório</span><select id="cRating">${['L','10','12','14','16','18'].map(t=>`<option ${x?.rating===t?'selected':''}>${t}</option>`).join('')}</select></label>
  <label class="field">Gênero <span class="req">obrigatório</span><input id="cGenre" value="${esc(x?.genre||'')}"></label>
  <label class="field">Status<select id="cStatus"><option ${x?.published!==false?'selected':''}>Publicado</option><option ${x?.published===false?'selected':''}>Rascunho</option></select></label>
  <label class="field span2">Descrição / sinopse <span id="descRequirement" class="req">obrigatório</span><textarea id="cDesc" rows="4">${esc(x?.desc||'')}</textarea></label>
  <div id="typeEditor" class="type-editor span2"></div>
  <label class="check"><input id="cFeatured" type="checkbox" ${x?.featured?'checked':''}><span>Destaque na home</span></label>
  <label class="check"><input id="cTrending" type="checkbox" ${x?.trending?'checked':''}><span>Em alta</span></label>
  <button class="primary-btn span2">Salvar conteúdo</button>
 </form></div>`;
 $('overlay').classList.remove('hidden');
 const asset=(id,label,accept,help,required=true,current=false)=>`<label class="field asset-field">${label} ${required?'<span class="req">obrigatório</span>':'<span class="optional">opcional</span>'}<input id="${id}" type="file" accept="${accept}"><small>${help}${current?' · já cadastrado':''}</small></label>`;
 const drawType=()=>{
  const t=$('cType').value,box=$('typeEditor');$('descRequirement').textContent=t==='Música'?'descrição ou letra':'obrigatório';$('descRequirement').className=t==='Música'?'optional':'req';
  if(t==='Filme')box.innerHTML=`<section class="media-editor"><div class="media-editor-head"><div><span class="media-icon">🎬</span><div><b>Filme</b><small>Capa vertical + banner horizontal + arquivo principal.</small></div></div><span class="quality-pill">7 itens essenciais</span></div><div class="form-grid">
    ${asset('cCover','Capa','image/*','Preferência: vertical 2:3',true,!!x?.cover)}${asset('cBanner','Banner','image/*','Preferência: horizontal 16:9',true,!!x?.banner)}
    <label class="field">Diretor <span class="req">obrigatório</span><input id="typeA" value="${esc(x?.director||'')}"></label><label class="field">Duração <span class="req">obrigatório</span><input id="typeDuration" placeholder="Ex.: 2h 08min" value="${esc(x?.duration||'')}"></label>
    <label class="field span2">Elenco <span class="optional">opcional</span><input id="typeCast" placeholder="Nome 1, Nome 2, Nome 3" value="${esc((x?.cast||[]).join(', '))}"></label>
    <label class="field">Áudio / idioma <span class="optional">opcional</span><input id="typeLanguages" placeholder="Português, English" value="${esc((x?.languages||[]).join(', '))}"></label><label class="field">Legendas <span class="optional">opcional</span><input id="typeSubtitles" placeholder="Português, English" value="${esc((x?.subtitles||[]).join(', '))}"></label>
    ${asset('typeMedia','Arquivo do filme','video/*','Arquivo de vídeo original; em produção será convertido para HLS',true,!!x?.mediaKey)}${asset('typeTrailer','Trailer / teaser','video/*','Opcional para a página do título',false,!!x?.trailerKey)}
   </div></section>`;
  else if(['Série','Anime','Dorama'].includes(t)){
   const who=t==='Anime'?'Estúdio':'Criador / produção',val=t==='Anime'?(x?.studio||''):(x?.creator||'');
   box.innerHTML=`<section class="media-editor"><div class="media-editor-head"><div><span class="media-icon">${t==='Anime'?'✦':'▣'}</span><div><b>${t}</b><small>Capa + banner da obra. Os vídeos ficam organizados em temporadas e episódios.</small></div></div><span class="quality-pill">episódios separados</span></div><div class="form-grid">
    ${asset('cCover','Capa','image/*','Preferência: vertical 2:3',true,!!x?.cover)}${asset('cBanner','Banner','image/*','Preferência: horizontal 16:9',true,!!x?.banner)}
    <label class="field">${who} <span class="req">obrigatório</span><input id="typeA" value="${esc(val)}"></label><label class="field">País / origem <span class="optional">opcional</span><input id="typeOrigin" value="${esc(x?.origin||'')}"></label>
    <label class="field">Episódios cadastrados<input disabled value="${x?.episodes?.length||0}"></label><label class="field">Temporadas cadastradas<input disabled value="${new Set((x?.episodes||[]).map(e=>e.season)).size||0}"></label>
    ${asset('typeTrailer','Trailer / teaser','video/*','Opcional para a página da obra',false,!!x?.trailerKey)}
    <div class="media-form-note span2"><b>Arquivos dos episódios</b><span>Depois de salvar a obra, use <strong>Mídia & Upload → Episódios</strong> para enviar E01, E02, E03 em lote.</span></div>
   </div></section>`
  }else if(t==='Livro')box.innerHTML=`<section class="media-editor"><div class="media-editor-head"><div><span class="media-icon">▤</span><div><b>Livro</b><small>Livro não precisa de banner. A capa é a imagem principal.</small></div></div><span class="quality-pill">sem banner</span></div><div class="form-grid">
    ${asset('cCover','Capa do livro','image/*','Preferência: vertical 2:3',true,!!x?.cover)}
    <label class="field">Autor <span class="req">obrigatório</span><input id="typeA" value="${esc(x?.author||'')}"></label><label class="field">Editora <span class="optional">opcional</span><input id="typePublisher" value="${esc(x?.publisher||'')}"></label>
    <label class="field">ISBN <span class="optional">opcional</span><input id="typeISBN" value="${esc(x?.isbn||'')}"></label><label class="field">Capítulos cadastrados<input disabled value="${x?.chapters?.length||0}"></label>
    ${asset('typeMedia','Arquivo do livro','application/pdf,.pdf,.epub,application/epub+zip','PDF ou EPUB. Pode usar capítulos internos ou arquivo completo.',true,!!x?.mediaKey)}
    <div class="media-form-note"><b>Banner removido</b><span>Para livros, a interface usa a própria capa quando precisa de imagem de destaque.</span></div>
   </div></section>`;
  else box.innerHTML=`<section class="media-editor"><div class="media-editor-head"><div><span class="media-icon">♫</span><div><b>Música</b><small>Sem banner. Capa quadrada, áudio e metadados da música.</small></div></div><span class="quality-pill">capa + áudio</span></div><div class="form-grid">
    ${asset('cCover','Capa da música / álbum','image/*','Preferência: quadrada 1:1',true,!!x?.cover)}
    <label class="field">Artista <span class="req">obrigatório</span><input id="typeA" value="${esc(x?.artist||'')}"></label><label class="field">Álbum <span class="optional">opcional</span><input id="typeB" value="${esc(x?.album||'')}"></label>
    <label class="field">Compositor <span class="optional">opcional</span><input id="typeComposer" value="${esc(x?.composer||'')}"></label><label class="field">Número da faixa <span class="optional">opcional</span><input id="typeTrackNo" type="number" min="1" value="${x?.trackNumber||''}"></label>
    ${asset('typeMedia','Arquivo da música','audio/*','MP3, M4A, AAC, WAV ou formato aceito pelo navegador',true,!!x?.mediaKey||!!x?.tracks?.length)}
    <label class="field span2">Letra <span class="optional">opcional — pode substituir a descrição no controle de qualidade</span><textarea id="typeLyrics" rows="7" placeholder="Cole a letra aqui, quando houver...">${esc(x?.lyrics||'')}</textarea></label>
    <div class="media-form-note span2"><b>Álbuns e EPs</b><span>Para várias faixas, salve a obra e use <strong>Mídia & Upload → Faixas de música</strong>.</span></div>
   </div></section>`;
 };
 drawType();$('cType').onchange=drawType;
 $('contentForm').onsubmit=async e=>{
  e.preventDefault();let a=D.catalog(),y=x?{...x}:{id:Date.now(),newRelease:true,progress:0};
  y.title=$('cTitle').value.trim();y.type=$('cType').value;y.year=+$('cYear').value;y.rating=$('cRating').value;y.genre=$('cGenre').value.trim();y.desc=$('cDesc').value.trim();y.published=$('cStatus').value==='Publicado';y.featured=$('cFeatured').checked;y.trending=$('cTrending').checked;
  const A=$('typeA')?.value?.trim(),B=$('typeB')?.value?.trim();
  if(y.type==='Filme'){y.director=A;y.duration=$('typeDuration')?.value?.trim();y.cast=splitList($('typeCast')?.value);y.languages=splitList($('typeLanguages')?.value);y.subtitles=splitList($('typeSubtitles')?.value)}
  if(['Série','Dorama'].includes(y.type)){y.creator=A;y.origin=$('typeOrigin')?.value?.trim()}if(y.type==='Anime'){y.studio=A;y.origin=$('typeOrigin')?.value?.trim()}
  if(y.type==='Livro'){y.author=A;y.publisher=$('typePublisher')?.value?.trim();y.isbn=$('typeISBN')?.value?.trim();delete y.banner}
  if(y.type==='Música'){y.artist=A;y.album=B;y.composer=$('typeComposer')?.value?.trim();y.trackNumber=+$('typeTrackNo')?.value||null;y.lyrics=$('typeLyrics')?.value?.trim();delete y.banner}
  const cf=$('cCover')?.files?.[0],bf=$('cBanner')?.files?.[0],mf=$('typeMedia')?.files?.[0],tf=$('typeTrailer')?.files?.[0];if(cf)y.cover=await dataUrl(cf);if(bf)y.banner=await dataUrl(bf);if(mf){y.mediaKey=await S.putMedia(`main_${y.id}_${Date.now()}`,mf);if(y.type==='Música'&&!(y.tracks?.length))y.tracks=[{number:y.trackNumber||1,title:y.title,duration:0,mediaKey:y.mediaKey,lyrics:y.lyrics||''}]}if(tf)y.trailerKey=await S.putMedia(`trailer_${y.id}_${Date.now()}`,tf);
  const q=D.quality(y);if(y.published&&!q.ready){LX.toast(`Salvo como rascunho: faltam ${q.checks.filter(c=>!c.ok).map(c=>c.label).join(', ')}.`);y.published=false}
  const i=a.findIndex(z=>z.id===y.id);i>=0?a[i]=y:a.unshift(y);D.saveCatalog(a);U.close();LX.toast('Conteúdo salvo.');U.state.libraryType=y.type;render('library')
 }
}
function splitList(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}
function dataUrl(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function del(id){if(!confirm('Excluir este conteúdo?'))return;D.saveCatalog(D.catalog().filter(x=>x.id!==id));render('library')}
function verify(id){const a=D.users(),x=a.find(z=>z.id===id);if(x)x.verified=!x.verified;D.saveUsers(a);render('community')}
function reqStatus(id,status){const a=D.requests(),x=a.find(z=>z.id===id);if(x){x.status=status;x.updated=Date.now();D.saveRequests(a)}render('requests')}
function premiumSet(email,plan){const a=D.subscriptions(),days=plan==='Anual'?365:30;a[email]={active:true,plan,started:Date.now(),until:Date.now()+days*86400000,demo:true};D.saveSubscriptions(a);D.track('admin_premium',{email,plan,active:true});LX.toast(`Premium ${plan.toLowerCase()} ativado.`);render('premium')}
function premiumOff(email){const a=D.subscriptions();a[email]={...(a[email]||{}),active:false,ended:Date.now()};D.saveSubscriptions(a);D.track('admin_premium',{email,active:false});LX.toast('Premium desativado.');render('premium')}
LX.admin={render,edit,del,verify,reqStatus,premiumSet,premiumOff};})();
