(()=>{const LX=window.LX,D=LX.data,S=LX.store,$=id=>document.getElementById(id),$$=s=>Array.from(document.querySelectorAll(s));
const state=LX.state={screen:'splash',mode:'Assistir',category:'Início',query:'',user:null,profile:null,hero:0,heroTimer:null,musicQueue:[],musicIndex:0,rankingPeriod:'Mensal',rankingKind:'Geral',readerSize:20,readerPaper:false,libraryType:'Todos'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));LX.esc=esc;
const show=id=>{['splash','auth','profiles','app','admin'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden');state.screen=id};LX.show=show;
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2300)};LX.toast=toast;
const initials=n=>(n||'LX').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();LX.initials=initials;
const greeting=()=>new Date().getHours()<12?'Bom dia':new Date().getHours()<18?'Boa tarde':'Boa noite';
const verified=(n,v)=>`${esc(n)}${v?'<span class="verified">✓</span>':''}`;LX.verified=verified;
const fmt=s=>{s=Math.floor(+s||0);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};LX.fmt=fmt;

const PROFILE_PRESETS={
  lx:{label:'LX',mark:'LX',bg:'linear-gradient(145deg,#173e70,#1184f4)'},
  plus:{label:'Plus',mark:'+',bg:'linear-gradient(145deg,#5530a8,#9b63ff)'},
  crown:{label:'Coroa',mark:'♛',bg:'linear-gradient(145deg,#6a4810,#e0a329)'},
  play:{label:'Play',mark:'▶',bg:'linear-gradient(145deg,#5a1924,#e24d62)'},
  music:{label:'Música',mark:'♫',bg:'linear-gradient(145deg,#18354e,#20a3c8)'},
  book:{label:'Livro',mark:'▤',bg:'linear-gradient(145deg,#174335,#36b985)'},
  neon:{label:'Neon',mark:'LX',bg:'linear-gradient(145deg,#10131d,#174a77)',glow:true},
  mono:{label:'Mono',mark:'LX',bg:'linear-gradient(145deg,#191919,#454545)'}
};LX.PROFILE_PRESETS=PROFILE_PRESETS;
function profileStyle(email=''){const all=S.read(S.keys.profileStyles,{});return all[email]||{preset:'lx'}}
function avatarHTML(name,email='',cls='profile-avatar'){const st=profileStyle(email);if(st.image)return `<div class="${cls} avatar-image" style="background-image:url('${st.image.replace(/'/g,'%27')}')"></div>`;const pr=PROFILE_PRESETS[st.preset]||PROFILE_PRESETS.lx;return `<div class="${cls} ${pr.glow?'avatar-glow':''}" style="background:${pr.bg}">${esc(pr.mark||initials(name))}</div>`}
LX.profileStyle=profileStyle;LX.avatarHTML=avatarHTML;

function posterWalls(){const arr=[...D.P,...D.P];$('wallA').innerHTML=arr.map(x=>`<div class="poster-tile" style="background-image:url('${x}')"></div>`).join('');$('wallB').innerHTML=[...arr].reverse().map(x=>`<div class="poster-tile" style="background-image:url('${x}')"></div>`).join('')}
function authTab(t){$('tabLogin').classList.toggle('active',t==='login');$('tabRegister').classList.toggle('active',t==='register');$('loginForm').classList.toggle('hidden',t!=='login');$('registerForm').classList.toggle('hidden',t!=='register')}
function renderProfiles(){const n=state.user?.name||'Usuário',email=state.user?.email||'';$('profileGrid').innerHTML=`<button class="profile-card" data-profile="main">${avatarHTML(n,email,'profile-avatar')}<strong>${esc(n)}</strong><small>Perfil principal</small></button><button class="profile-card" data-profile="kids"><div class="profile-avatar kids-avatar">K</div><strong>Kids</strong><small>Conteúdo infantil</small></button>`;$$('[data-profile]').forEach(b=>b.onclick=()=>{state.profile={id:b.dataset.profile,name:b.dataset.profile==='kids'?'Kids':n,kids:b.dataset.profile==='kids'};$('profileBtn').innerHTML=b.dataset.profile==='kids'?'<span>K</span>':avatarHTML(n,email,'avatar-inline');renderApp();show('app')})}
function categories(){return state.mode==='Assistir'?['Início','Filmes','Séries','Animes','Doramas','Minha Lista','Pedidos','Ranking LX']:state.mode==='Ler'?['Início','Livros','Minha Lista','Pedidos','Ranking LX']:['Início','Música','Minha Lista','Pedidos','Ranking LX']}
function renderCategories(){$('categoryNav').innerHTML=categories().map(c=>`<button class="${c===state.category?'active':''}" data-cat="${c}">${c}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{const c=b.dataset.cat;if(c==='Ranking LX')return LX.openRanking();if(c==='Pedidos')return LX.openRequests();state.category=c;renderApp()})}
function allowed(){return state.mode==='Assistir'?['Filme','Série','Anime','Dorama']:state.mode==='Ler'?['Livro']:['Música']}
function items(){let a=D.catalog().filter(x=>x.published!==false&&allowed().includes(x.type));if(state.profile?.kids)a=a.filter(x=>!['16','18'].includes(String(x.rating)));if(state.category==='Minha Lista')a=a.filter(x=>D.myList().includes(x.id));else if(state.category!=='Início'){const map={Filmes:'Filme',Séries:'Série',Animes:'Anime',Doramas:'Dorama',Livros:'Livro',Música:'Música'};if(map[state.category])a=a.filter(x=>x.type===map[state.category])}if(state.query)a=D.search(a,state.query);return a}
function renderHero(){let f=items().filter(x=>x.featured);if(!f.length)f=items().slice(0,4);if(!f.length){$('hero').innerHTML='';return}state.hero=Math.min(state.hero,f.length-1);$('hero').innerHTML=f.map((x,i)=>`<article class="hero-slide ${i===state.hero?'active':''}"><div class="hero-bg" style="background-image:url('${x.banner||x.cover}')"></div><div class="hero-copy"><span class="eyebrow">${state.mode.toUpperCase()} · LX SELECT</span><h1>${esc(x.title)}</h1><div class="hero-meta"><span>${x.year}</span><span>${esc(x.rating)}</span><span>${esc(x.genre)}</span><span>${esc(x.type)}</span></div><p>${esc(x.desc)}</p><div class="hero-actions"><button class="primary-btn" onclick="LX.primary(${x.id})">${x.type==='Livro'?'▤ Ler agora':x.type==='Música'?'♫ Ouvir':'▶ Assistir'}</button><button class="secondary-btn" onclick="LX.detail(${x.id})">ⓘ Mais informações</button></div></div></article>`).join('')+`<div class="hero-dots">${f.map((_,i)=>`<button class="${i===state.hero?'active':''}" data-dot="${i}"></button>`).join('')}</div>`;$$('[data-dot]').forEach(d=>d.onclick=()=>{state.hero=+d.dataset.dot;renderHero();heroTimer(f.length)});heroTimer(f.length)}
function heroTimer(n){clearInterval(state.heroTimer);if(n>1)state.heroTimer=setInterval(()=>{state.hero=(state.hero+1)%n;renderHero()},7600)}
function renderWelcome(){const h=D.history(),entries=Object.values(h).filter(Boolean),sub=D.subscriptions()[state.user?.email||''];$('welcome').innerHTML=`<div class="welcome-card"><div><span class="eyebrow">${state.mode.toUpperCase()} ${sub?.active?'<span class="premium-user-pill">PREMIUM</span>':''}</span><h2>${greeting()}, <span>${esc(state.profile?.name||state.user?.name||'você')}</span></h2><p>${state.mode==='Assistir'?'Continue suas histórias ou descubra algo novo.':state.mode==='Ler'?'Retome sua leitura ou abra um novo universo.':'Sua trilha continua exatamente de onde parou.'}</p></div><div class="mode-summary"><div><strong>${entries.length}</strong><small>EM PROGRESSO</small></div><div><strong>${D.myList().length}</strong><small>MINHA LISTA</small></div><div><strong>${items().length}</strong><small>NO CATÁLOGO</small></div></div></div>`}
function card(x,progress,rank){const h=D.history()[x.id],p=h?.progress??x.progress??0,r=D.ratings()[x.id],listed=D.myList().includes(x.id);return `<article class="card" onclick="LX.detail(${x.id})"><div class="card-art" style="background-image:url('${x.cover||x.banner}')"><div class="card-badges">${rank?`<span>#${rank}</span>`:''}${x.newRelease?'<span>NOVO</span>':''}${r?`<span>★ ${r}</span>`:''}${listed?'<span>✓ LISTA</span>':''}</div><div class="card-copy"><div class="card-title">${esc(x.title)}</div><div class="card-meta">${x.year} · ${esc(x.type)} · ${esc(x.genre)}</div></div>${progress&&p?`<div class="progress-line"><i style="width:${Math.min(100,p)}%"></i></div>`:''}</div></article>`}
function rail(title,sub,a,progress=false,top10=false){if(!a.length)return'';const id='r'+Math.random().toString(36).slice(2,8);return `<section class="rail-section"><div class="rail-head"><div><h2>${title}</h2><p>${sub}</p></div><span>${a.length} títulos</span></div><div class="rail-wrap"><button class="rail-arrow left" onclick="LX.scroll('${id}',-1)">‹</button><div class="rail" id="${id}">${a.map((x,i)=>card(x,progress,top10?i+1:null)).join('')}</div><button class="rail-arrow right" onclick="LX.scroll('${id}',1)">‹</button></div></section>`}
function renderHome(){const a=items();if(state.query){$('homeContent').innerHTML=rail(`Resultados para “${esc(state.query)}”`,'Busca tolerante a erros por título, elenco, autor, artista, gênero e tags.',a);return}if(state.category!=='Início'){$('homeContent').innerHTML=rail(state.category,'Tudo nesta categoria.',a);return}const h=D.history(),pref=D.preferences()[state.user?.email||'']||{},cont=a.filter(x=>h[x.id]?.progress>0||x.progress>0),recs=D.recommendation(a,h,D.ratings(),pref).slice(0,12),top=[...a].sort((x,y)=>(y.trending?1:0)-(x.trending?1:0)).slice(0,10);let html='';if(cont.length)html+=rail(state.mode==='Ler'?'Continuar lendo':state.mode==='Ouvir'?'Ouvir novamente':'Continuar assistindo','Retome exatamente de onde parou.',cont,true);if(recs.length){const why=pref.genres?.length?`Preferências: ${pref.genres.slice(0,3).join(', ')}. Também usamos histórico, notas e tags.`:'Baseado no seu histórico, avaliações, gêneros e tags. Você pode escolher seus gêneros no Perfil.';html+=rail('Para você',why,recs)}html+=rail('Top 10 LX','Os títulos mais fortes neste momento.',top,false,true);html+=rail('Em alta','O que está chamando atenção.',a.filter(x=>x.trending));html+=rail('Lançamentos','Novidades recém-chegadas.',a.filter(x=>x.newRelease));[...new Set(a.map(x=>x.genre))].slice(0,5).forEach(g=>html+=rail(g,`Seleção em ${g.toLowerCase()}.`,a.filter(x=>x.genre===g)));$('homeContent').innerHTML=html}
function renderApp(){renderCategories();renderHero();renderWelcome();renderHome();updateNoticeCount()}
function scroll(id,d){const e=$(id);e?.scrollBy({left:d*e.clientWidth*.82,behavior:'smooth'})}
function close(){$('overlay').classList.add('hidden')}function closePlayer(){$('playerOverlay').classList.add('hidden');$('videoEl')?.pause()}function closeReader(){$('readerOverlay').classList.add('hidden')}
function updateNoticeCount(){const c=D.notices().filter(x=>!x.read).length;$('notifyCount').textContent=c;$('notifyCount').style.display=c?'grid':'none'}
LX.ui={$, $$, state, esc, show, toast, initials, posterWalls, authTab, renderProfiles, renderApp, renderHome, renderCategories, items, close, closePlayer, closeReader, scroll, updateNoticeCount};
})();
