/* LX Music v29.3: artwork and control icons shared across music surfaces. */
(()=>{
  'use strict';
  const LX=window.LX=window.LX||{},fallback='assets/lx-music-fallback.svg';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const valid=v=>{const s=String(v??'').trim();return s&&!/^(?:undefined|null|none|about:blank)$/i.test(s)&&!/[<>]/.test(s)&&/^(?:https?:\/\/|blob:|data:image\/|assets\/|\.\/assets\/)/i.test(s)?s:''};
  function ytId(ref){const raw=String(ref??'').trim();if(/^youtube:[\w-]{11}$/i.test(raw))return raw.slice(8);try{const u=new URL(raw);if(!/(^|\.)(?:youtube\.com|youtu\.be)$/.test(u.hostname))return '';const id=u.hostname.endsWith('youtu.be')?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.match(/^\/(?:embed|shorts|live)\/([\w-]{11})/)?.[1];return /^[\w-]{11}$/.test(id||'')?id:''}catch{return ''}}
  function candidates(item={},content={}){const yt=ytId(item.mediaKey||item.url||content.mediaKey||content.url||content.tracks?.[0]?.mediaKey);const spotify=item.spotifyArtwork||item.images?.[0]?.url||item.album?.images?.[0]?.url||content.spotifyArtwork||content.album?.images?.[0]?.url;return [...new Set([item.cover,item.artwork?.url,item.albumCover,item.album?.cover,content.cover,content.image,content.carouselImage,content.banner,yt?`https://i.ytimg.com/vi/${yt}/hqdefault.jpg`:'',spotify,fallback].map(valid).filter(Boolean))]}
  const url=(item,content)=>candidates(item,content)[0]||fallback;
  const safeBackground=(item,content)=>`url(${JSON.stringify(url(item,content))})`;
  function markup(item,content={},className='',alt=''){const list=candidates(item,content);return `<span class="lx-artwork ${esc(className)}"><img src="${esc(list[0])}" data-lx-artwork="${encodeURIComponent(JSON.stringify(list))}" alt="${esc(alt)}" loading="lazy" decoding="async"></span>`}
  function bind(img,list){if(!img)return;const urls=list?.length?list:[fallback],previous=img.dataset.lxArtworkActive;img.dataset.lxArtworkActive=JSON.stringify(urls);img.dataset.lxArtworkIndex='0';img.onload=()=>{const surface=img.closest('.lx-music-feature,.lx-v27-now-playing');surface?.style.setProperty('--artwork-bg',`url(${JSON.stringify(img.currentSrc||img.src)})`)};img.onerror=()=>{const choices=JSON.parse(img.dataset.lxArtworkActive||'[]'),next=Number(img.dataset.lxArtworkIndex||0)+1;if(next>=choices.length){img.onerror=null;return}img.dataset.lxArtworkIndex=String(next);img.src=choices[next]};if(!previous||previous!==img.dataset.lxArtworkActive||!img.getAttribute('src'))img.src=urls[0];else if(img.complete&&img.naturalWidth===0)img.onerror()}
  function hydrate(root=document){root.querySelectorAll?.('img[data-lx-artwork]').forEach(img=>{let list=[];try{list=JSON.parse(decodeURIComponent(img.dataset.lxArtwork||''))}catch{}bind(img,list)})}
  function set(element,item,content={}){if(!element)return;let img=element.matches?.('img')?element:element.querySelector('img[data-lx-artwork]');if(!img){element.replaceChildren();img=document.createElement('img');img.setAttribute('data-lx-artwork','');img.alt='';element.appendChild(img)}bind(img,candidates(item,content));element.classList.add('lx-artwork');return img}
  const paths={play:'<path d="m8 5 11 7-11 7z"/>',pause:'<path d="M8 5v14M16 5v14"/>',prev:'<path d="M6 5v14m13-14-10 7 10 7z"/>',next:'<path d="M18 5v14M5 5l10 7-10 7z"/>',heart:'<path d="M20.8 8.7c0 5-8.8 10.9-8.8 10.9S3.2 13.7 3.2 8.7a4.7 4.7 0 0 1 8.8-2.3 4.7 4.7 0 0 1 8.8 2.3z"/>',queue:'<path d="M4 6h16M4 11h16M4 16h9m5-1v5m-2.5-2.5h5"/>',repeat:'<path d="m17 3 3 3-3 3M4 6h16m-13 9-3 3 3 3m13-3H4"/>',shuffle:'<path d="M4 5h3c5 0 5 14 10 14h3m-3-3 3 3-3 3M4 19h3c2.2 0 3.6-2.8 5-5m2-4c1.3-2.3 2.5-5 6-5m-3-3 3 3-3 3"/>',volume:'<path d="M4 9v6h4l5 4V5L8 9zm12-1a5 5 0 0 1 0 8m2-11a9 9 0 0 1 0 14"/>',close:'<path d="m5 5 14 14M19 5 5 19"/>',down:'<path d="m5 9 7 7 7-7"/>',lyrics:'<path d="M8 5h12M8 10h12M8 15h8M8 20h6M4 5h.01M4 10h.01M4 15h.01"/>',external:'<path d="M14 5h5v5M19 5l-9 9m7 1v4H5V7h4"/>',home:'<path d="m3 11 9-7 9 7m-16-1v10h14V10M9 20v-7h6v7"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/>',library:'<path d="M4 5h16v14H4zM8 5v14m4-11h5m-5 4h5"/>',history:'<path d="M3 12a9 9 0 1 0 3-7m-3 0v5h5m4-4v6l4 2"/>',plus:'<path d="M12 4v16M4 12h16"/>',up:'<path d="m5 15 7-7 7 7"/>'};
  function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.play}</svg>`}
  function initIcons(){const ids={musicShuffle:'shuffle',musicPrev:'prev',musicNext:'next',musicRepeat:'repeat',musicLikeBtn:'heart',musicLyricsBtn:'lyrics',musicQueueBtn:'queue',musicClose:'close',musicProviderToggle:'external'};Object.entries(ids).forEach(([id,name])=>{const node=document.getElementById(id);if(node)node.innerHTML=icon(name)});const like=document.getElementById('musicLikeBtn'),info=document.querySelector('#musicDock .music-info');if(like&&info&&!info.contains(like)){info.appendChild(like);like.addEventListener('click',event=>event.stopPropagation())}const volume=document.querySelector('.music-right-controls>span');if(volume)volume.innerHTML=icon('volume')}
  const pending=new Map();
  async function enrichSpotify(item){const id=String(item?.mediaKey||'').match(/^spotify:track:([\w]+)$/i)?.[1];if(!id||url(item)!==fallback||!LX.cloud?.db?.())return;if(pending.has(id))return pending.get(id);const task=(async()=>{try{let {data,error}=await LX.cloud.db().functions.invoke('lx-spotify-catalog',{body:{action:'track',id}});let record=!error?data?.data:null;if(!record&&String(item.title||'').trim().length>1){({data,error}=await LX.cloud.db().functions.invoke('lx-spotify-catalog',{body:{action:'search',q:`${item.title} ${item.artist||''}`.trim().slice(0,100),limit:20}}));record=!error?data?.data?.tracks?.items?.find(track=>String(track.id)===id):null}if(!record)return;const cover=valid(record.album?.images?.[0]?.url||record.images?.[0]?.url);if(!cover)return;item.spotifyArtwork=cover;item.cover=cover;item.title=String(record.name||item.title||'').trim()||item.title;item.artist=(record.artists||[]).map(a=>a.name).filter(Boolean).join(', ')||item.artist;item.duration=Number(record.duration_ms||0)/1000||item.duration;document.dispatchEvent(new CustomEvent('lx:music-artwork-updated',{detail:{item,id}}))}catch(error){console.warn('LX Spotify artwork',error)}finally{pending.delete(id)}})();pending.set(id,task);return task}
  LX.artwork={fallback,candidates,url,safeBackground,markup,set,hydrate,icon,initIcons,enrichSpotify};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initIcons,{once:true});else initIcons();
})();
