/* LX Plus — audio effects + ambient + floating music player + adaptive cinema. */

/* Optional MP3 audio adjustments. */
(()=>{'use strict';
 const LX=window.LX,audio=document.getElementById('musicAudio'),button=document.getElementById('musicEffectsBtn');
 if(!LX||!audio||!button)return;
 const defaults={enabled:false,gain:100,bass:0,preset:'original'},presets={original:{gain:100,bass:0},suave:{gain:105,bass:2},grave:{gain:110,bass:8},energia:{gain:125,bass:5}};
 const store=()=>LX.store?.read?.(LX.store.keys.playerPrefs,{})||{};
 const state={...defaults,...(store().musicEffects||{})};
 let context=null,source=null,shelf=null,volume=null,limiter=null;
 const external=()=>document.getElementById('musicDock')?.classList.contains('external-provider');
 const clamp=(v,lo,hi)=>Math.min(hi,Math.max(lo,Number(v)||0));
 const save=()=>LX.store?.write?.(LX.store.keys.playerPrefs,{...store(),musicEffects:{...state}});
 function graph(){if(source)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)throw new Error('Este navegador não oferece ajustes de áudio.');context=LX.__musicAudioContext||new A();LX.__musicAudioContext=context;source=context.createMediaElementSource(audio);shelf=context.createBiquadFilter();shelf.type='lowshelf';shelf.frequency.value=110;volume=context.createGain();limiter=context.createDynamicsCompressor();limiter.threshold.value=-4;limiter.knee.value=0;limiter.ratio.value=16;limiter.attack.value=.003;limiter.release.value=.16;shelf.connect(volume);volume.connect(limiter);limiter.connect(context.destination)}
 function apply(){if(!source)return;const now=context.currentTime;source.disconnect();if(state.enabled){source.connect(shelf);shelf.gain.setTargetAtTime(state.bass,now,.025);volume.gain.setTargetAtTime(state.gain/100,now,.025)}else source.connect(context.destination)}
 function paint(message=''){const root=document.getElementById('lxMusicEffectsPanel');button.classList.toggle('active',state.enabled);button.setAttribute('aria-pressed',String(state.enabled));if(!root)return;root.querySelector('[name=active]').checked=state.enabled;root.querySelector('[name=gain]').value=state.gain;root.querySelector('[data-gain]').textContent=state.gain+'%';root.querySelector('[name=bass]').value=state.bass;root.querySelector('[data-bass]').textContent=(state.bass>0?'+':'')+state.bass+' dB';root.querySelector('[name=preset]').value=state.preset;root.querySelector('[data-effect-status]').textContent=message||(!state.enabled?'Efeitos desligados · som original':external()?'Ajustes salvos. O YouTube/Spotify usa o player oficial; abra um MP3 para ouvi-los.':'Ajustes aplicados ao MP3 do catálogo.')}
 async function enable(on){try{if(on){graph();state.enabled=true;apply();await context.resume()}else{state.enabled=false;apply()}save();paint();LX.toast?.(on?'Ajustes MP3 ligados.':'Ajustes MP3 desligados.')}catch(err){state.enabled=false;try{apply()}catch{}paint(err.message||'Não foi possível ativar os ajustes.')}}
 function open(){let root=document.getElementById('lxMusicEffectsPanel');if(root){root.remove();return}root=document.createElement('aside');root.id='lxMusicEffectsPanel';root.className='lx-music-effects-panel';root.setAttribute('aria-label','Ajustes de áudio MP3');root.innerHTML='<header><strong>Qualidade da sua música</strong><button type="button" data-close aria-label="Fechar ajustes">×</button></header><label class="lx-effect-toggle"><input name="active" type="checkbox"> Ativar ajustes para MP3</label><label>Preset<select name="preset"><option value="original">Original</option><option value="suave">Suave</option><option value="grave">Mais graves</option><option value="energia">Energia</option><option value="personalizado">Personalizado</option></select></label><label>Amplificar <output data-gain></output><input name="gain" type="range" min="50" max="180" step="1"></label><label>Aumento de grave <output data-bass></output><input name="bass" type="range" min="-6" max="12" step="1"></label><p data-effect-status role="status"></p><small>O limitador reduz distorção em ganhos altos. Estes controles alteram a reprodução, não a qualidade original do arquivo.</small>';document.body.append(root);root.querySelector('[data-close]').onclick=()=>root.remove();root.querySelector('[name=active]').onchange=e=>enable(e.target.checked);root.querySelector('[name=preset]').onchange=e=>{state.preset=e.target.value;if(presets[state.preset])Object.assign(state,presets[state.preset]);apply();save();paint()};for(const key of ['gain','bass'])root.querySelector('[name='+key+']').oninput=e=>{state[key]=clamp(e.target.value,key==='gain'?50:-6,key==='gain'?180:12);state.preset='personalizado';apply();save();paint()};paint()}
 button.onclick=open;audio.addEventListener('play',()=>{if(state.enabled){try{graph();apply();if(context.state==='suspended')context.resume().catch(()=>{})}catch(err){state.enabled=false;paint(err.message)}}});document.addEventListener('lx:music-changed',()=>paint());document.addEventListener('lx:music-closed',()=>document.getElementById('lxMusicEffectsPanel')?.remove());LX.audioEffects={open,state:()=>({...state}),resume:()=>state.enabled?context?.resume?.():Promise.resolve()};
})();

/* Ambient visual loader. */
(()=>{'use strict';
 const CSS_ID='lxAmbientV1Css',LAYER_ID='lxAmbientV1';
 function mount(){let link=document.getElementById(CSS_ID);if(!link){link=document.createElement('link');link.id=CSS_ID;link.rel='stylesheet';document.head.appendChild(link)}link.href='lxplus.ambient-v2.css?v=20260926-2';if(!document.getElementById(LAYER_ID)){const layer=document.createElement('div');layer.id=LAYER_ID;layer.setAttribute('aria-hidden','true');layer.innerHTML='<i class="lx-ambient-blob-a"></i><i class="lx-ambient-blob-b"></i><i class="lx-ambient-arc-a"></i><i class="lx-ambient-arc-b"></i><i class="lx-ambient-line"></i>';document.body.prepend(layer)}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();

/* LX Music V6 — move anywhere, resize from every side/corner, minimize and expand. */
(()=>{'use strict';
 const POS_KEY='lx_music_float_pos_v6',SIZE_KEY='lx_music_float_size_v6',STATE_KEY='lx_music_float_state_v6';
 const dock=()=>document.getElementById('musicDock'),audio=()=>document.getElementById('musicAudio');
 let drag=null,resize=null,lastPositionUpdate=0;
 const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
 const read=(k,d=null)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
 const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
 const sizeLimits=()=>({minW:innerWidth<=520?220:260,minH:innerWidth<=520?70:104,maxW:Math.max(240,innerWidth-16),maxH:Math.max(90,innerHeight-16)});
 function bounds(el,x,y,w=el.getBoundingClientRect().width,h=el.getBoundingClientRect().height){const pad=8;return{x:clamp(x,pad,Math.max(pad,innerWidth-w-pad)),y:clamp(y,pad,Math.max(pad,innerHeight-h-pad))}}
 function setXY(el,x,y,save=true){const r=el.getBoundingClientRect(),p=bounds(el,x,y,r.width,r.height);el.style.setProperty('left',p.x+'px','important');el.style.setProperty('top',p.y+'px','important');el.style.setProperty('right','auto','important');el.style.setProperty('bottom','auto','important');if(save)write(POS_KEY,{x:Math.round(p.x),y:Math.round(p.y)});return p}
 function setSize(el,w,h,save=true){const l=sizeLimits(),nw=clamp(w,l.minW,l.maxW),nh=clamp(h,l.minH,l.maxH);el.style.setProperty('width',nw+'px','important');el.style.setProperty('height',nh+'px','important');el.style.setProperty('min-width',l.minW+'px','important');el.style.setProperty('max-width',l.maxW+'px','important');el.style.setProperty('max-height',l.maxH+'px','important');if(save)write(SIZE_KEY,{w:Math.round(nw),h:Math.round(nh)});const r=el.getBoundingClientRect();setXY(el,r.left,r.top,save);return{w:nw,h:nh}}
 function defaultGeometry(save=true){const el=dock();if(!el)return;requestAnimationFrame(()=>{el.classList.remove('lx-music-minimized');const w=Math.min(370,Math.max(220,innerWidth-24)),h=124;setSize(el,w,h,save);setXY(el,Math.max(8,innerWidth-w-18),innerWidth<=700?66:18,save);write(STATE_KEY,{minimized:false,expanded:false})})}
 function restoreGeometry(){const el=dock();if(!el)return;const p=read(POS_KEY),s=read(SIZE_KEY),st=read(STATE_KEY,{minimized:false,expanded:false});requestAnimationFrame(()=>{if(s?.w&&s?.h)setSize(el,+s.w,+s.h,false);else setSize(el,Math.min(370,Math.max(220,innerWidth-24)),124,false);if(p&&Number.isFinite(+p.x)&&Number.isFinite(+p.y))setXY(el,+p.x,+p.y,false);else{const r=el.getBoundingClientRect();setXY(el,Math.max(8,innerWidth-r.width-18),innerWidth<=700?66:18,false)}el.classList.toggle('lx-music-minimized',!!st.minimized)})}
 function beginDrag(e,handle){const el=dock();if(!el||resize)return;if(e.button!==0&&e.pointerType!=='touch')return;const r=el.getBoundingClientRect();drag={id:e.pointerId,dx:e.clientX-r.left,dy:e.clientY-r.top};el.classList.add('lx-is-dragging');handle?.setPointerCapture?.(e.pointerId);e.preventDefault()}
 function moveDrag(e){const el=dock();if(!el||!drag||drag.id!==e.pointerId)return;setXY(el,e.clientX-drag.dx,e.clientY-drag.dy,false);e.preventDefault()}
 function endDrag(e,handle){const el=dock();if(!el||!drag||drag.id!==e.pointerId)return;const r=el.getBoundingClientRect();write(POS_KEY,{x:Math.round(r.left),y:Math.round(r.top)});drag=null;el.classList.remove('lx-is-dragging');try{handle?.releasePointerCapture?.(e.pointerId)}catch{}}
 function beginResize(e,dir,handle){const el=dock();if(!el||drag||el.classList.contains('lx-music-minimized'))return;if(e.button!==0&&e.pointerType!=='touch')return;const r=el.getBoundingClientRect();resize={id:e.pointerId,dir,x:e.clientX,y:e.clientY,left:r.left,top:r.top,w:r.width,h:r.height};el.classList.add('lx-is-resizing');handle.setPointerCapture?.(e.pointerId);e.preventDefault();e.stopPropagation()}
 function moveResize(e){const el=dock();if(!el||!resize||resize.id!==e.pointerId)return;const l=sizeLimits(),dx=e.clientX-resize.x,dy=e.clientY-resize.y,d=resize.dir;let left=resize.left,top=resize.top,w=resize.w,h=resize.h;if(d.includes('e'))w=resize.w+dx;if(d.includes('s'))h=resize.h+dy;if(d.includes('w')){w=resize.w-dx;left=resize.left+dx}if(d.includes('n')){h=resize.h-dy;top=resize.top+dy}w=clamp(w,l.minW,l.maxW);h=clamp(h,l.minH,l.maxH);if(d.includes('w'))left=resize.left+(resize.w-w);if(d.includes('n'))top=resize.top+(resize.h-h);const p=bounds(el,left,top,w,h);el.style.setProperty('width',w+'px','important');el.style.setProperty('height',h+'px','important');el.style.setProperty('left',p.x+'px','important');el.style.setProperty('top',p.y+'px','important');el.style.setProperty('right','auto','important');el.style.setProperty('bottom','auto','important');e.preventDefault();e.stopPropagation()}
 function endResize(e,handle){const el=dock();if(!el||!resize||resize.id!==e.pointerId)return;const r=el.getBoundingClientRect();write(POS_KEY,{x:Math.round(r.left),y:Math.round(r.top)});write(SIZE_KEY,{w:Math.round(r.width),h:Math.round(r.height)});resize=null;el.classList.remove('lx-is-resizing');try{handle.releasePointerCapture?.(e.pointerId)}catch{}}
 function toggleMinimize(){const el=dock();if(!el)return;const st=read(STATE_KEY,{minimized:false,expanded:false});if(!st.minimized){const r=el.getBoundingClientRect();write(SIZE_KEY,{w:Math.round(r.width),h:Math.round(r.height)});el.classList.add('lx-music-minimized');setSize(el,Math.min(260,innerWidth-16),74,false);st.minimized=true}else{el.classList.remove('lx-music-minimized');const s=read(SIZE_KEY,{w:370,h:124});setSize(el,+s.w||370,+s.h||124,false);st.minimized=false}write(STATE_KEY,st);const r=el.getBoundingClientRect();setXY(el,r.left,r.top,true)}
 function toggleExpand(){const el=dock();if(!el)return;el.classList.remove('lx-music-minimized');const st=read(STATE_KEY,{minimized:false,expanded:false});if(!st.expanded){const r=el.getBoundingClientRect();write(SIZE_KEY,{w:Math.round(r.width),h:Math.round(r.height)});setSize(el,Math.min(560,innerWidth-16),Math.min(190,innerHeight-16),true);st.expanded=true;st.minimized=false}else{setSize(el,Math.min(370,innerWidth-16),124,true);st.expanded=false}write(STATE_KEY,st)}
 function ensureControls(){const el=dock();if(!el)return;let h=el.querySelector('.lx-music-drag-handle');if(!h){h=document.createElement('div');h.className='lx-music-drag-handle';h.innerHTML='<span class="lx-drag-dots">•••</span><span class="lx-drag-label">MOVER</span><button type="button" class="lx-float-tool lx-min-btn" title="Minimizar" aria-label="Minimizar player">−</button><button type="button" class="lx-float-tool lx-size-btn" title="Aumentar ou voltar ao tamanho normal" aria-label="Alterar tamanho do player">⤢</button>';h.title='Arraste o player para qualquer lugar';h.setAttribute('aria-label','Mover player de música');h.tabIndex=0;el.prepend(h)}
 if(h.dataset.lxDragBound!=='1'){h.dataset.lxDragBound='1';h.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;beginDrag(e,h)});h.addEventListener('pointermove',moveDrag);h.addEventListener('pointerup',e=>endDrag(e,h));h.addEventListener('pointercancel',e=>endDrag(e,h));h.addEventListener('dblclick',e=>{if(e.target.closest('button'))return;e.preventDefault();defaultGeometry(true)});h.addEventListener('keydown',e=>{const el=dock();if(!el)return;const r=el.getBoundingClientRect(),step=e.shiftKey?40:16;let x=r.left,y=r.top,handled=true;if(e.key==='ArrowLeft')x-=step;else if(e.key==='ArrowRight')x+=step;else if(e.key==='ArrowUp')y-=step;else if(e.key==='ArrowDown')y+=step;else if(e.key==='Home'){defaultGeometry(true);e.preventDefault();return}else handled=false;if(handled){e.preventDefault();setXY(el,x,y,true)}})}
 h.querySelector('.lx-min-btn')?.addEventListener('click',e=>{e.stopPropagation();toggleMinimize()});h.querySelector('.lx-size-btn')?.addEventListener('click',e=>{e.stopPropagation();toggleExpand()});
 const info=el.querySelector('.music-info');if(info&&!info.dataset.lxDragBound){info.dataset.lxDragBound='1';info.title='Segure e arraste para mover o player';info.addEventListener('pointerdown',e=>{if(e.target.closest('button,a,input'))return;beginDrag(e,info)});info.addEventListener('pointermove',moveDrag);info.addEventListener('pointerup',e=>endDrag(e,info));info.addEventListener('pointercancel',e=>endDrag(e,info))}
 for(const dir of ['n','e','s','w','ne','nw','se','sw']){let r=el.querySelector('.lx-r-'+dir);if(!r){r=document.createElement('i');r.className='lx-resize-handle lx-r-'+dir;r.dataset.dir=dir;r.setAttribute('aria-hidden','true');el.appendChild(r)}if(r.dataset.lxResizeBound!=='1'){r.dataset.lxResizeBound='1';r.addEventListener('pointerdown',e=>beginResize(e,dir,r));r.addEventListener('pointermove',moveResize);r.addEventListener('pointerup',e=>endResize(e,r));r.addEventListener('pointercancel',e=>endResize(e,r))}}
 restoreGeometry()}
 function coverURL(){const cover=document.getElementById('musicCover');if(!cover)return'';const img=cover.querySelector?.('img');if(img?.src)return img.src;const bg=getComputedStyle(cover).backgroundImage||'';const m=bg.match(/url\(["']?(.*?)["']?\)/);return m?.[1]||''}
 function metadata(){if(!('mediaSession'in navigator))return;const a=audio(),title=document.getElementById('musicTitle')?.textContent?.trim()||'LX Music',artist=document.getElementById('musicArtist')?.textContent?.trim()||'LX Plus',art=coverURL();try{navigator.mediaSession.metadata=new MediaMetadata({title,artist,album:'LX Plus',artwork:art?[{src:art}]:[]})}catch{}if(a)try{navigator.mediaSession.playbackState=a.paused?'paused':'playing'}catch{}}
 function positionState(force=false){const a=audio();if(!a||!('mediaSession'in navigator)||typeof navigator.mediaSession.setPositionState!=='function'||!Number.isFinite(a.duration)||a.duration<=0)return;const now=Date.now();if(!force&&now-lastPositionUpdate<900)return;lastPositionUpdate=now;try{navigator.mediaSession.setPositionState({duration:a.duration,playbackRate:a.playbackRate||1,position:Math.min(a.duration,Math.max(0,a.currentTime||0))})}catch{}}
 function click(id){document.getElementById(id)?.click()}
 function setupMediaSession(){const a=audio();if(!a)return;a.setAttribute('playsinline','');a.setAttribute('preload','metadata');if('mediaSession'in navigator){const set=(name,fn)=>{try{navigator.mediaSession.setActionHandler(name,fn)}catch{}};set('play',()=>a.play().catch(()=>{}));set('pause',()=>a.pause());set('previoustrack',()=>click('musicPrev'));set('nexttrack',()=>click('musicNext'));set('seekbackward',d=>{a.currentTime=Math.max(0,(a.currentTime||0)-(d.seekOffset||10))});set('seekforward',d=>{a.currentTime=Math.min(a.duration||Infinity,(a.currentTime||0)+(d.seekOffset||10))});set('seekto',d=>{if(Number.isFinite(d.seekTime))a.currentTime=Math.max(0,Math.min(a.duration||d.seekTime,d.seekTime))})}for(const ev of ['play','pause','loadedmetadata','durationchange'])a.addEventListener(ev,()=>{metadata();positionState(true)});a.addEventListener('timeupdate',()=>positionState(false));document.addEventListener('lx:music-changed',()=>setTimeout(()=>{metadata();positionState(true)},30))}
 function clampCurrent(){const el=dock();if(!el)return;const r=el.getBoundingClientRect();setSize(el,r.width,r.height,true);setXY(el,r.left,r.top,true)}
 function boot(){ensureControls();setupMediaSession();metadata();window.addEventListener('resize',clampCurrent,{passive:true});window.addEventListener('orientationchange',()=>setTimeout(clampCurrent,90),{passive:true});LX.musicFloat={reset:()=>defaultGeometry(true),moveTo:(x,y)=>{const el=dock();if(el)setXY(el,+x||8,+y||8,true)},resizeTo:(w,h)=>{const el=dock();if(el)setSize(el,+w||370,+h||124,true)},minimize:toggleMinimize,expand:toggleExpand}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();

/* Adaptive full-screen cinema fit. */
(()=>{'use strict';
 const VISUAL_ID='lxVisualV4Css',FIT_KEY='lx_video_fit_v4';
 function loadVisual(){let link=document.getElementById(VISUAL_ID);if(!link){link=document.createElement('link');link.id=VISUAL_ID;link.rel='stylesheet';document.head.appendChild(link)}link.href='lxplus.visual-v4.css?v=20260926-3'}
 function readFit(){try{return localStorage.getItem(FIT_KEY)==='contain'?'contain':'fill'}catch{return'fill'}}function writeFit(mode){try{localStorage.setItem(FIT_KEY,mode)}catch{}}
 function enhanceCinema(host){const shadow=host?.shadowRoot;if(!shadow)return false;const stage=shadow.getElementById('stage'),video=shadow.getElementById('video');if(!stage||!video)return false;if(!shadow.getElementById('lxAdaptiveFillV4')){const style=document.createElement('style');style.id='lxAdaptiveFillV4';style.textContent='#stage #video{width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:cover!important;object-position:center center!important;background:#000!important}#stage.lx-fit-contain-v4 #video{object-fit:contain!important}#poster{width:100%!important;height:100%!important;object-fit:cover!important;object-position:center center!important}.actions #lxFitV4{font-size:15px;font-weight:900}.actions #lxFitV4.active{border-color:rgba(177,83,255,.58);box-shadow:0 0 18px rgba(138,43,226,.25)}@media(max-width:460px){.actions #lxFitV4{display:none!important}}';shadow.appendChild(style)}const actions=shadow.querySelector('.actions');let button=shadow.getElementById('lxFitV4');if(actions&&!button){button=document.createElement('button');button.id='lxFitV4';button.className='round';button.type='button';button.setAttribute('aria-label','Alternar preenchimento do vídeo');actions.prepend(button)}const apply=()=>{const mode=readFit();stage.classList.toggle('lx-fit-contain-v4',mode==='contain');stage.dataset.lxScreen=innerWidth>=innerHeight?'landscape':'portrait';if(button){button.textContent=mode==='fill'?'▣':'□';button.classList.toggle('active',mode==='fill');button.title=mode==='fill'?'Tela preenchida · toque para ajustar sem corte':'Vídeo ajustado · toque para preencher a tela'}};if(button&&!button.dataset.lxBound){button.dataset.lxBound='1';button.addEventListener('click',e=>{e.stopPropagation();writeFit(readFit()==='fill'?'contain':'fill');apply()})}if(!video.dataset.lxFitBound){video.dataset.lxFitBound='1';video.addEventListener('loadedmetadata',apply);video.addEventListener('emptied',apply)}if(!stage.dataset.lxResizeBound&&'ResizeObserver'in window){stage.dataset.lxResizeBound='1';const ro=new ResizeObserver(apply);ro.observe(stage)}apply();return true}
 function scan(){const host=document.getElementById('lxGlobalCinema');if(host)requestAnimationFrame(()=>enhanceCinema(host))}
 function boot(){loadVisual();scan();const obs=new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes){if(node?.nodeType!==1)continue;if(node.id==='lxGlobalCinema'||node.querySelector?.('#lxGlobalCinema'))setTimeout(scan,0)}});obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('resize',scan,{passive:true});window.addEventListener('orientationchange',()=>setTimeout(scan,80),{passive:true})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
