const fs=require('fs'),path=require('path'),assert=require('assert');
const root=__dirname,read=p=>fs.readFileSync(path.join(root,p),'utf8');
const index=read('index.html'),v40=read('lxplus.v40.js'),css=read('lxplus.v40.css'),sw=read('service-worker.js'),album=read('lxplus.album-grouping.js'),sql=read('supabase/migrations/20260925_lxplus_v40.sql');
const build='V40-COMPLETE-20260925',bugfix='V40-BUGFIX-20260927';
for(const f of ['index.html','lxplus.bundle.js','lxplus.album-grouping.js','lxplus.v40.js','lxplus.v40.css','service-worker.js','manifest.webmanifest','assets/lx-music-v40.svg'])assert(fs.existsSync(path.join(root,f)),`missing ${f}`);
assert(index.includes('lxplus.v40.js')&&index.includes('lxplus.v40.css'),'v40 layer not loaded');
assert(index.includes(build),'v40 core build marker mismatch');
assert(sw.includes(bugfix),'v40 bugfix shell marker mismatch');
for(const token of ['renderTop10','renderHomeEnhancements','bindFloatingPlayer','publishPresence','openRanking','resolveStream','renderLiveAdmin','bindAdminAutosave','renderLinkHealth','renderErrors','createPoll','toggleSavedMessage'])assert(v40.includes(token),`missing v40 feature ${token}`);
for(const token of ['lx40-top10','lx40-premiere','lx40-pulse','lx40-podium','#musicDock.music-dock','lx40-draft-note'])assert(css.includes(token),`missing CSS ${token}`);
for(const token of ['V40-BUGFIX-20260927','__LX_BUGFIX_BUILD','__lxProtectedReadGuard','LX_AUTH_WAIT','lxBugfixDrag','setProperty(\'left\'','setProperty(\'top\''])assert(album.includes(token),`missing bugfix ${token}`);
assert(album.includes("get(){return root.LX?.store}"),'v27 S/store runtime alias missing');
assert(album.includes("table==='lx_catalog'||table==='lx_notifications'"),'anonymous protected-table guard missing');
assert(album.includes("localStorage.setItem('lx40:player-pos'"),'floating player position persistence missing');
for(const token of ['lx_presence','lx_rank_seasons','lx_rank_scores','lx_rank_events','lx_saved_messages','lx_message_pins','lx_polls','lx_client_errors','lx_viewer_profiles'])assert(sql.includes(token),`missing migration ${token}`);
for(const token of ['lx_v40_thread_member','INVALID_REFERENCE','recent_events','previous_life'])assert(sql.includes(token),`missing security guard ${token}`);
assert(!/lx_(?:pins_auth_read|polls_read)[\s\S]{0,120}using\s*\(\s*true\s*\)/i.test(sql),'conversation privacy policy is too broad');
assert(v40.includes("from('lx_settings').select('value')")&&v40.includes("persistFeatureFlags"),'feature flags are not cloud synchronized');
assert(v40.includes('rankAuditRows')&&v40.includes('Auditoria antifraude'),'ranking audit panel missing');
assert(v40.includes('rankCache.get(rankState.season)'),'shared ranking card ignores cloud rank');
assert(!/drop\s+table|truncate\s+table/i.test(sql),'destructive SQL found');
assert(!/BEGIN (?:RSA |EC )?PRIVATE KEY[\s\S]{80,}/.test(index+v40+album),'private key leaked');
console.log('LX Plus v40 static integration + stability hotfix: PASS');
