-- LX Plus v25.40 — Call Sync + persistent user notifications

alter table public.lx_calls add column if not exists caller_heartbeat_at timestamptz;
alter table public.lx_calls add column if not exists callee_heartbeat_at timestamptz;

-- Close only clearly stale legacy calls left open by older builds.
update public.lx_calls
set status='ended', ended_at=coalesce(ended_at,now()), updated_at=now()
where status='accepted' and answered_at < now()-interval '4 hours';

create or replace function public.lx_start_call(p_other uuid, p_mode text default 'video'::text)
returns uuid
language plpgsql
security definer
set search_path to 'public','auth'
as $$
declare a uuid; b uuid; cid uuid;
begin
  if p_mode not in ('video','audio') then p_mode:='video'; end if;
  select x.a,x.b into a,b from public.lx_pair_users(p_other) x;
  if not exists(select 1 from public.lx_friendships f where f.user_low=a and f.user_high=b and f.status='accepted') then raise exception 'friendship required'; end if;
  if not exists(select 1 from public.lx_profiles p where p.user_id=p_other and p.approved and p.calls_enabled) then raise exception 'calls unavailable'; end if;
  update public.lx_calls set status='missed',ended_at=now(),updated_at=now()
    where callee_id=p_other and status='ringing' and created_at < now()-interval '90 seconds';
  insert into public.lx_calls(caller_id,callee_id,mode,status,caller_heartbeat_at)
    values(auth.uid(),p_other,p_mode,'ringing',now()) returning id into cid;
  return cid;
end;$$;

create or replace function public.lx_respond_call(p_call_id uuid, p_accept boolean)
returns text
language plpgsql
security definer
set search_path to 'public','auth'
as $$
declare s text;
begin
  if not exists(select 1 from public.lx_calls where id=p_call_id and callee_id=auth.uid() and status='ringing') then raise exception 'call unavailable'; end if;
  s:=case when p_accept then 'accepted' else 'rejected' end;
  update public.lx_calls
     set status=s,
         answered_at=case when p_accept then now() else answered_at end,
         ended_at=case when p_accept then ended_at else now() end,
         callee_heartbeat_at=case when p_accept then now() else callee_heartbeat_at end,
         updated_at=now()
   where id=p_call_id;
  return s;
end;$$;

create or replace function public.lx_end_call(p_call_id uuid)
returns boolean
language plpgsql
security definer
set search_path to 'public','auth'
as $$
declare v_status text;
begin
  select status into v_status from public.lx_calls
   where id=p_call_id and (caller_id=auth.uid() or callee_id=auth.uid())
   for update;
  if not found or v_status not in ('ringing','accepted') then return false; end if;

  -- Persist a hangup signal BEFORE changing status so every client has a second
  -- realtime path to terminate the remote UI.
  insert into public.lx_call_signals(call_id,sender_id,kind,payload)
  values(p_call_id,auth.uid(),'hangup',jsonb_build_object('at',extract(epoch from now())*1000,'source','rpc'));

  update public.lx_calls
     set status=case when v_status='ringing' then 'missed' else 'ended' end,
         ended_at=now(), updated_at=now()
   where id=p_call_id;
  return true;
end;$$;

create or replace function public.lx_call_heartbeat(p_call_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'public','auth'
as $$
declare c public.lx_calls%rowtype; peer_at timestamptz;
begin
  select * into c from public.lx_calls
   where id=p_call_id and (caller_id=auth.uid() or callee_id=auth.uid())
   for update;
  if not found then raise exception 'call unavailable'; end if;

  if c.caller_id=auth.uid() then
    update public.lx_calls set caller_heartbeat_at=now(),updated_at=case when status in ('ringing','accepted') then updated_at else updated_at end where id=p_call_id;
  else
    update public.lx_calls set callee_heartbeat_at=now(),updated_at=case when status in ('ringing','accepted') then updated_at else updated_at end where id=p_call_id;
  end if;

  select * into c from public.lx_calls where id=p_call_id;
  peer_at:=case when c.caller_id=auth.uid() then c.callee_heartbeat_at else c.caller_heartbeat_at end;
  return jsonb_build_object(
    'id',c.id,'status',c.status,'mode',c.mode,'answered_at',c.answered_at,'ended_at',c.ended_at,
    'peer_heartbeat_at',peer_at,'updated_at',c.updated_at
  );
end;$$;

revoke all on function public.lx_call_heartbeat(uuid) from public, anon;
grant execute on function public.lx_call_heartbeat(uuid) to authenticated, service_role;

create table if not exists public.lx_user_notifications(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'system',
  title text not null,
  message text not null default '',
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists lx_user_notifications_user_created_idx on public.lx_user_notifications(user_id,created_at desc);
create index if not exists lx_user_notifications_unread_idx on public.lx_user_notifications(user_id,read_at) where read_at is null;
alter table public.lx_user_notifications enable row level security;

drop policy if exists "lx user notifications own read" on public.lx_user_notifications;
create policy "lx user notifications own read" on public.lx_user_notifications for select to authenticated using(user_id=auth.uid());
drop policy if exists "lx user notifications own update" on public.lx_user_notifications;
create policy "lx user notifications own update" on public.lx_user_notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists "lx user notifications own delete" on public.lx_user_notifications;
create policy "lx user notifications own delete" on public.lx_user_notifications for delete to authenticated using(user_id=auth.uid());
grant select,update,delete on public.lx_user_notifications to authenticated;

create or replace function public.lx_notify_new_message()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
declare v_name text; v_preview text;
begin
  select coalesce(nullif(name,''),'Contato') into v_name from public.lx_profiles where user_id=new.sender_id;
  v_name:=coalesce(v_name,'Contato');
  v_preview:=case new.kind
    when 'audio' then 'Enviou uma mensagem de áudio'
    when 'image' then 'Enviou uma foto'
    when 'file' then 'Enviou um arquivo'
    when 'sticker' then 'Enviou uma figurinha'
    else left(coalesce(nullif(new.body,''),'Nova mensagem'),140)
  end;
  insert into public.lx_user_notifications(user_id,kind,title,message,data)
  values(new.recipient_id,'message','Mensagem de '||v_name,v_preview,
    jsonb_build_object('sender_id',new.sender_id,'client_id',new.client_id,'message_id',new.id));
  return new;
end;$$;

drop trigger if exists lx_messages_notify_recipient on public.lx_messages;
create trigger lx_messages_notify_recipient after insert on public.lx_messages for each row execute function public.lx_notify_new_message();

create or replace function public.lx_notify_call_result()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
declare v_name text;
begin
  if old.status is distinct from new.status and new.status='missed' then
    select coalesce(nullif(name,''),'Contato') into v_name from public.lx_profiles where user_id=new.caller_id;
    insert into public.lx_user_notifications(user_id,kind,title,message,data)
    values(new.callee_id,'call','Chamada perdida',coalesce(v_name,'Contato')||' tentou ligar para você',jsonb_build_object('call_id',new.id,'caller_id',new.caller_id,'mode',new.mode));
  end if;
  return new;
end;$$;

drop trigger if exists lx_calls_notify_result on public.lx_calls;
create trigger lx_calls_notify_result after update of status on public.lx_calls for each row execute function public.lx_notify_call_result();

revoke all on function public.lx_notify_new_message() from public, anon, authenticated;
revoke all on function public.lx_notify_call_result() from public, anon, authenticated;

-- Add personal notification table to Realtime only once.
do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='lx_user_notifications') then
    alter publication supabase_realtime add table public.lx_user_notifications;
  end if;
end$$;

-- v25.40 hotfix: older schema only allowed offer/answer/ice.
alter table public.lx_call_signals drop constraint if exists lx_call_signals_kind_check;
alter table public.lx_call_signals add constraint lx_call_signals_kind_check check (kind in ('offer','answer','ice','reaction','share','hangup'));
