import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
import {compactPublicMetadata} from '../tools/compact-public-metadata.mjs';import {catalogUpdateSql} from '../tools/catalog-updates.mjs';
const require=createRequire(import.meta.url),{PGlite}=require(path.join(process.env.LX_QA_NODE_MODULES||path.resolve('tools/catalog-qa/node_modules'),'@electric-sql/pglite'));
const db=new PGlite();await db.exec('create table lx_catalog(id bigint primary key,payload jsonb,published boolean,updated_at timestamptz default now());');
const p={id:7,type:'Música',title:'Faixa',artist:'LX QA',album:'Álbum',cover:'https://example.invalid/cover.jpg',banner:'https://example.invalid/cover.jpg',metadataUrl:'https://music.apple.com/br/album/1?i=2',externalProviderUrl:'https://music.apple.com/br/album/1?i=2',catalogOnly:true,metadataOnly:true,availability:'coming_soon',mediaKey:'',tracks:[{number:1,title:'Faixa',artist:'LX QA',album:'Álbum',cover:'https://example.invalid/cover.jpg',mediaKey:''}]};
await db.query('insert into lx_catalog(id,payload,published) values (1,$1,true),(7,$2,true)',[{title:'Owner file',mediaKey:'cloud:owned'},p]);
const baseline={original_ids:[1],original_count:1,fingerprint:(await db.query("select md5(string_agg(id::text||payload::text||published::text,'' order by id)) as h from lx_catalog where id=1")).rows[0].h};
const hash=async()=>(await db.query('select md5(payload::text||published::text) as h from lx_catalog where id=7')).rows[0].h;
const compact=compactPublicMetadata(p);for(const key of ['title','artist','album','cover','metadataUrl'])assert.equal(compact[key],p[key]);assert.equal(compact.tracks,undefined);
let update={id:7,payload:compact,expected_hash:await hash()};const result=async sql=>(await db.exec(sql)).find(x=>x.rows?.[0]?.targets_unchanged!==undefined).rows[0];
assert.deepEqual(await result(catalogUpdateSql([update],baseline)),{originals_unchanged:true,targets_unchanged:true,updated:1});
assert.equal((await result(catalogUpdateSql([update],baseline))).updated,0,'Stale target must not be overwritten');
assert.throws(()=>catalogUpdateSql([{...update,id:1}],baseline),/ORIGINAL_OR_INVALID_TARGET/);
assert.throws(()=>catalogUpdateSql([update],{...baseline,original_count:'1; delete from lx_catalog'}),/INVALID_UPDATE_BATCH/);
const official={...compact,mediaKey:'youtube:abcdefghijk',youtubeVideoId:'abcdefghijk',externalMusicUrl:'https://www.youtube.com/watch?v=abcdefghijk',metadataOnly:false,availability:'available',sourceVerified:true};
assert.throws(()=>compactPublicMetadata(official),/ONLY_EMPTY/);update={id:7,payload:official,expected_hash:await hash()};
assert.deepEqual(await result(catalogUpdateSql([update],baseline,{officialMusic:true})),{originals_unchanged:true,targets_unchanged:true,updated:1});
assert.throws(()=>catalogUpdateSql([{...update,payload:{...official,sourceVerified:false}}],baseline,{officialMusic:true}),/UNVERIFIED_MUSIC_SOURCE/);
assert.equal((await db.query('select payload->>\'mediaKey\' as media from lx_catalog where id=1')).rows[0].media,'cloud:owned');
await db.close();console.log('PASS guarded imported-row updates: metadata retained; originals excluded; stale writes blocked; only verified official music sources accepted.');
