import assert from 'node:assert/strict';
import {parseReference,publicUrl,allowedUrl,tmdbItem,googleBook,openBook,musicItem,rankSources,mergeCards,parseImportText,metadataOnly,healthStatus} from '../supabase/functions/_shared/universal-core.mjs';
const ref=parseReference('https://www.themoviedb.org/movie/11-star-wars');assert.deepEqual(ref,{provider:'tmdb',namespace:'movie',id:'11'});
assert.equal(parseReference('https://watch.plex.tv/pt-BR/movie/leprechaun').provider,'plex');
assert.equal(parseReference('https://books.google.com/books?id=BookId').id,'BookId');
assert.equal(parseReference('https://openlibrary.org/works/OL123W/name').namespace,'work');
for(const value of ['http://example.com/movie','javascript:alert(1)','https://localhost/a','https://127.0.0.1/a','https://2130706433/a','https://0x7f000001/a','https://[::1]/a','https://user:pass@example.com/a','https://example.com:8443/a'])assert.equal(publicUrl(value),'',value);
assert.equal(allowedUrl('https://allowed.test.evil.test/file.mp4',['allowed.test']),'');
assert.throws(()=>parseReference('https://themoviedb.org.evil.test/movie/11'));
const movie=tmdbItem({id:11,title:'Nome traduzido',original_title:'Original',origin_country:['JP'],genres:[{id:16,name:'Animação'}],overview:'Sinopse',poster_path:'/poster.jpg',credits:{cast:[{name:'Pessoa'}]},videos:{results:[{site:'YouTube',key:'abcdefghijk',type:'Trailer'}]}},'movie');
assert.equal(movie.kind,'anime');assert.equal(movie.external_ids[0].namespace,'movie');assert.equal(movie.metadata.trailers.length,1);
const japaneseSeries=tmdbItem({id:12,name:'Drama',origin_country:['JP'],genres:[{id:18,name:'Drama'}]},'tv');assert.equal(japaneseSeries.kind,'dorama');assert(japaneseSeries.tags.includes('J-Drama'));
const comedy=tmdbItem({id:13,name:'Comédia',origin_country:['JP'],genres:[{id:35,name:'Comédia'}]},'tv');assert.equal(comedy.kind,'series','Country alone must not classify a dorama');
const book=googleBook({id:'book',volumeInfo:{title:'Livro',description:'<p>Uma descrição</p>',industryIdentifiers:[{type:'ISBN_13',identifier:'978-1234567890'}],authors:['Autora'],imageLinks:{thumbnail:'http://books.google.com/cover.png'}}});assert.equal(book.description,'Uma descrição');assert.equal(book.metadata.authors[0],'Autora');assert(!Object.hasOwn(book,'readUrl'));assert(book.cover.startsWith('https://'));
assert.equal(openBook({key:'/works/OL123W',title:'Título'}).external_ids[0].external_id,'OL123W');
const song=musicItem({id:'uuid',title:'Faixa',length:200000,'artist-credit':[{name:'Cantora',artist:{id:'artist'}}],isrcs:['BRABC1234567']});assert.equal(song.duration,200);assert.equal(song.metadata.artist,'Cantora');assert(!Object.hasOwn(song,'url'));
const sources=[{id:'a',authorized:true,drm:'none',source_type:'direct',status:'online',priority:1},{id:'b',authorized:true,drm:'none',source_type:'lx',status:'slow',priority:9},{id:'c',authorized:true,drm:'protected',source_type:'lx',status:'online'},{id:'d',authorized:false,drm:'none',source_type:'lx',status:'online'},{id:'e',authorized:true,drm:'none',source_type:'direct',status:'expired'}];assert.deepEqual(rankSources(sources).map(x=>x.id),['b','a']);assert.deepEqual(rankSources(sources,{exclude:['b']}).map(x=>x.id),['a']);
assert.equal(rankSources([{...sources[0],region:['US']}],{region:'BR'}).length,0);
assert.equal(rankSources([{...sources[0],episode_id:'e'}],{episode:'other'}).length,0);
assert.equal(healthStatus(403,100),'unauthorized');assert.equal(healthStatus(451,100),'region_blocked');assert.equal(healthStatus(200,3000),'slow');
assert.equal(mergeCards([movie,{...movie,kind:'movie'}]).length,1);
assert.equal(mergeCards([movie,{...movie,external_ids:[{provider:'tmdb',namespace:'tv',external_id:'11'}]}]).length,2);
assert.deepEqual(parseImportText('url,title\n"https://example.com/?a=1,b=2","Uma, coisa"\nhttps://example.com/second,Texto','csv'),['https://example.com/?a=1,b=2','https://example.com/second']);
assert.deepEqual(parseImportText('{"items":["tmdb:movie:11"]}','json'),['tmdb:movie:11']);assert.throws(()=>parseImportText('"bad','csv'));assert.throws(()=>parseImportText('{}','json'));
assert(!Object.hasOwn(metadataOnly({...movie,url:'secret',mediaKey:'private'}),'url'));
console.log('PASS catalog contracts: reference/provider validation; private-network URLs; taxonomy; IDs; metadata without playback; source ranking, DRM, permissions, regions and failover exclusions; CSV/JSON; stripping media fields.');
