(()=>{
const LX=window.LX,S=LX.store;
let client=null,currentAuth=null,currentProfile=null,adminDirectory=[],syncTimer=null,channels=[];
const USER_STATE_KEYS=new Set([S.keys.history,S.keys.list,S.keys.ratings,S.keys.preferences,S.keys.profileStyles,S.keys.theme,S.keys.accent,S.keys.layoutMode,S.keys.motion,S.keys.playerPrefs,S.keys.noticeReads]);
function cfg(){return LX.config.supabase||{}}
function publicKey(){const c=cfg();return c.publishableKey||c.anonKey||''}
function enabled(){const c=cfg();return !!(window.supabase&&/^https:\/\/.+\.supabase\.co\/?$/i.test(c.url||'')&&publicKey().length>20)}
function db(){if(!enabled())return null;if(!client)client=window.supabase.createClient(cfg().url.replace(/\/$/,''),publicKey(),{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client}
function uuid(x){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(x||''))}
function user(){return currentAuth}
function profile(){return currentProfile}
function isAdmin(){return !!currentProfile?.admin}
function bucketFor(folder){return ['assets','profiles'].includes(folder)?(cfg().assetBucket||'lx-assets'):(cfg().mediaBucket||'lx-media')}
function publicUrl(path,bucket){const c=db();if(!c||!path)return null;return c.storage.from(bucket||cfg().assetBucket||'lx-assets').getPublicUrl(path).data.publicUrl}
async function mediaUrl(path,expires=3600){const c=db();if(!c||!path)return null;const {data,error}=await c.storage.from(cfg().mediaBucket||'lx-media').createSignedUrl(path,expires);if(error)throw error;return data?.signedUrl||null}
function safeName(name){return String(name||'file').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120)}
async function uploadFile(key,file,folder='media'){
 const c=db();if(!c)throw new Error('CLOUD_NOT_CONFIGURED');if(!currentAuth)throw new Error('AUTH_REQUIRED');
 const path=`${folder}/${currentAuth.id}/${Date.now()}_${safeName(key||file?.name)}`,bucket=bucketFor(folder);
 const {error}=await c.storage.from(bucket).upload(path,file,{upsert:false,contentType:file?.type||undefined,cacheControl:'3600'});
 if(error)throw error;return `cloud:${path}`
}
function cache(k,v){S.writeLocal(k,v)}
function mapCatalog(rows){return (rows||[]).map(r=>({...r.payload,id:Number(r.id),published:r.published!==false}))}
async function refreshCatalog(){const c=db();if(!c)return;const {data,error}=await c.from('lx_catalog').select('id,payload,published,updated_at').order('updated_at',{ascending:false});if(!error&&data?.length)cache(S.keys.catalog,mapCatalog(data))}
async function refreshNotices(){const c=db();if(!c)return;const {data,error}=await c.from('lx_notifications').select('id,title,message,published_at,created_at').eq('published',true).order('created_at',{ascending:false}).limit(100);if(!error){const reads=new Set(S.read(S.keys.noticeReads,[]));const n=(data||[]).map(x=>({id:x.id,title:x.title,text:x.message,time:x.published_at?new Date(x.published_at).toLocaleDateString('pt-BR'):'Agora',read:reads.has(x.id)}));cache(S.keys.notices,n)}}
async function refreshBranding(){const c=db();if(!c)return;const {data,error}=await c.from('lx_settings').select('value').eq('key','branding').maybeSingle();if(!error&&data?.value)cache(S.keys.globalBranding,data.value)}
async function saveBranding(value){const c=db();if(!c||!isAdmin())throw new Error('ADMIN_REQUIRED');const {error}=await c.from('lx_settings').upsert({key:'branding',value,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error;cache(S.keys.globalBranding,value)}
async function initPublic(){if(!enabled())return {enabled:false};try{await Promise.all([refreshCatalog(),refreshNotices(),refreshBranding()]);subscribePublic();return {enabled:true}}catch(e){console.warn('LX cloud public init',e);return {enabled:true,error:e}}}
function subscribePublic(){const c=db();if(!c||channels.length)return;const ch=c.channel('lxplus-public-v20').on('postgres_changes',{event:'*',schema:'public',table:'lx_catalog'},()=>refreshCatalog().then(()=>LX.ui?.renderApp?.())).on('postgres_changes',{event:'*',schema:'public',table:'lx_notifications'},()=>refreshNotices().then(()=>LX.ui?.updateNoticeCount?.())).on('postgres_changes',{event:'*',schema:'public',table:'lx_settings'},()=>refreshBranding().then(()=>{LX.applyBranding?.();LX.ui?.renderApp?.()})).subscribe();channels.push(ch)}
async function ensureProfile(authUser){const c=db();const {data,error}=await c.from('lx_profiles').select('*').eq('user_id',authUser.id).maybeSingle();if(error)throw error;if(data)return data;const row={user_id:authUser.id,name:authUser.user_metadata?.name||authUser.email?.split('@')[0]||'Usuário',ranking_visible:authUser.user_metadata?.ranking_visible!==false};const ins=await c.from('lx_profiles').insert(row).select().single();if(ins.error)throw ins.error;return ins.data}
async function hydrateUser(authUser){if(!enabled()||!authUser)return null;currentAuth=authUser;const c=db();const p=await ensureProfile(authUser);currentProfile={...p,admin:false};const {data:adm}=await c.rpc('lx_am_i_admin');currentProfile.admin=!!adm;await refreshCatalog();
 const [stateRes,subRes,profilesRes,reqRes]=await Promise.all([
  c.from('lx_user_state').select('data').eq('user_id',authUser.id).maybeSingle(),
  c.from('lx_subscriptions').select('*').eq('user_id',authUser.id).maybeSingle(),
  c.from('lx_profiles').select('user_id,name,verified,ranking_visible,watched_hours,listened_hours,read_count,streak,created_at').order('created_at',{ascending:true}),
  c.from('lx_requests').select('id,kind,media_type,title,message,votes,status,created_at,user_name').order('created_at',{ascending:false})
 ]);
 let st=stateRes.data?.data||{};
 if(!Object.keys(st).length){st=await prepareLocalStateForCloud();await c.from('lx_user_state').upsert({user_id:authUser.id,data:st,updated_at:new Date().toISOString()},{onConflict:'user_id'})}
 cache(S.keys.history,st.history||{});cache(S.keys.list,st.list||[]);cache(S.keys.ratings,st.ratings||{});cache(S.keys.preferences,{[authUser.email]:st.preferences||{genres:[],autoplay:true}});cache(S.keys.profileStyles,{[authUser.email]:st.profileStyle||{preset:'lx'}});cache(S.keys.noticeReads,st.noticeReads||[]);if(st.theme)cache(S.keys.theme,st.theme);if(st.accent)cache(S.keys.accent,st.accent);if(st.layoutMode)cache(S.keys.layoutMode,st.layoutMode);if(st.motion)cache(S.keys.motion,st.motion);if(st.playerPrefs)cache(S.keys.playerPrefs,st.playerPrefs);await refreshNotices();
 let users=(profilesRes.data||[]).map(x=>({id:x.user_id,name:x.name,email:x.user_id===authUser.id?authUser.email:'',verified:x.verified,visible:x.ranking_visible,watched:+x.watched_hours||0,listened:+x.listened_hours||0,read:x.read_count||0,streak:x.streak||0,created:x.created_at?+new Date(x.created_at):null}));
 adminDirectory=[];
 if(currentProfile.admin){const dir=await c.rpc('lx_admin_user_directory');if(!dir.error){adminDirectory=dir.data||[];const byId=new Map(adminDirectory.map(x=>[x.user_id,x]));users=users.map(x=>({...x,email:byId.get(x.id)?.email||x.email,admin:byId.get(x.id)?.admin||false}));const sr=await c.from('lx_subscriptions').select('*');if(!sr.error){const subs={};(sr.data||[]).forEach(s=>{const em=byId.get(s.user_id)?.email;if(em)subs[em]=subToLocal(s)});cache(S.keys.subscriptions,subs)}await refreshAnalytics()}}
 cache(S.keys.users,users);
 if(!currentProfile.admin){cache(S.keys.subscriptions,{[authUser.email]:subRes.data?subToLocal(subRes.data):{active:false}})}
 const reqs=(reqRes.data||[]).map(r=>({id:Number(r.id),kind:r.kind,mediaType:r.media_type,title:r.title,message:r.message||'',votes:r.votes||1,status:r.status,created:+new Date(r.created_at),userEmail:authUser.email,userName:r.user_name||'Usuário',voters:[authUser.email]}));cache(S.keys.requests,reqs);
 subscribeUser();return toAppUser(authUser,currentProfile)
}
function subToLocal(s){return {active:!!s.active,plan:s.plan||'Mensal',started:s.created_at?+new Date(s.created_at):Date.now(),until:s.current_period_end?+new Date(s.current_period_end):null,status:s.status||'active',cloud:true,userId:s.user_id}}
function toAppUser(a,p){return {id:a.id,name:p?.name||a.user_metadata?.name||a.email?.split('@')[0]||'Usuário',email:a.email,admin:!!p?.admin,verified:!!p?.verified,ranking:p?.ranking_visible!==false,cloud:true}}
function subscribeUser(){const c=db();if(!c||!currentAuth)return;channels.filter(x=>x.topic?.includes('lxplus-user')).forEach(x=>c.removeChannel(x));channels=channels.filter(x=>!x.topic?.includes('lxplus-user'));const uid=currentAuth.id;const ch=c.channel(`lxplus-user-${uid}`).on('postgres_changes',{event:'*',schema:'public',table:'lx_user_state',filter:`user_id=eq.${uid}`},()=>hydrateUser(currentAuth).then(()=>LX.ui?.renderApp?.())).on('postgres_changes',{event:'*',schema:'public',table:'lx_subscriptions',filter:`user_id=eq.${uid}`},()=>hydrateUser(currentAuth).then(()=>LX.ui?.renderApp?.())).subscribe();channels.push(ch)}
async function signUp({name,email,password,ranking}){const c=db();if(!c)throw new Error('CLOUD_NOT_CONFIGURED');const {data,error}=await c.auth.signUp({email,password,options:{data:{name,ranking_visible:!!ranking},emailRedirectTo:location.origin+location.pathname}});if(error)throw error;if(!data.session)return {user:{id:data.user?.id,name,email,needsConfirmation:true,cloud:true},needsConfirmation:true};const appUser=await hydrateUser(data.user);return {user:appUser}}
async function signIn(email,password){const c=db();if(!c)throw new Error('CLOUD_NOT_CONFIGURED');const {data,error}=await c.auth.signInWithPassword({email,password});if(error)throw error;return {user:await hydrateUser(data.user)}}
async function resume(){const c=db();if(!c)return null;const {data,error}=await c.auth.getSession();if(error||!data.session?.user)return null;return {user:await hydrateUser(data.session.user)}}
async function signOut(){if(db())await db().auth.signOut().catch(()=>{});currentAuth=null;currentProfile=null;adminDirectory=[];cache(S.keys.users,[]);cache(S.keys.subscriptions,{});await refreshCatalog().catch(()=>{});await refreshNotices().catch(()=>{});await refreshBranding().catch(()=>{})}
async function resetPassword(email){const c=db();if(!c)throw new Error('CLOUD_NOT_CONFIGURED');const redirect=(LX.config.siteUrl||location.origin+location.pathname).replace(/\/$/,'/')+'?recovery=1';const {error}=await c.auth.resetPasswordForEmail(email,{redirectTo:redirect});if(error)throw error;return true}
async function updatePassword(password){const c=db();if(!c)throw new Error('CLOUD_NOT_CONFIGURED');const {error}=await c.auth.updateUser({password});if(error)throw error;history.replaceState({},document.title,location.pathname);return true}
function isRecoveryFlow(){return /(?:[?#&](?:type=recovery|recovery=1))/.test(location.href)}
function buildState(){const email=currentAuth?.email||'';return {history:S.read(S.keys.history,{}),list:S.read(S.keys.list,[]),ratings:S.read(S.keys.ratings,{}),preferences:(S.read(S.keys.preferences,{})||{})[email]||{genres:[],autoplay:true},profileStyle:(S.read(S.keys.profileStyles,{})||{})[email]||{preset:'lx'},theme:S.read(S.keys.theme,'dark'),accent:S.read(S.keys.accent,'#42a5ff'),layoutMode:S.read(S.keys.layoutMode,'cinema'),motion:S.read(S.keys.motion,'full'),playerPrefs:S.read(S.keys.playerPrefs,{volume:1,muted:false}),noticeReads:S.read(S.keys.noticeReads,[])}}
async function dataUriBlob(uri){const r=await fetch(uri);return r.blob()}
async function prepareLocalStateForCloud(){const st=buildState();if(st.profileStyle?.image?.startsWith?.('data:')){try{const b=await dataUriBlob(st.profileStyle.image),k=await uploadFile('profile_migrated.png',b,'profiles');st.profileStyle={...st.profileStyle,image:publicUrl(k.replace(/^cloud:/,''),cfg().assetBucket||'lx-assets')};const all=S.read(S.keys.profileStyles,{});all[currentAuth.email]=st.profileStyle;cache(S.keys.profileStyles,all)}catch(e){console.warn('LX profile migration',e)}}return st}
function onLocalWrite(k){if(!enabled()||!currentAuth||!USER_STATE_KEYS.has(k))return;clearTimeout(syncTimer);syncTimer=setTimeout(syncUserState,550)}
async function syncUserState(){const c=db();if(!c||!currentAuth)return;const {error}=await c.from('lx_user_state').upsert({user_id:currentAuth.id,data:buildState(),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)console.warn('LX state sync',error)}
async function saveCatalog(items){const c=db();if(!c||!isAdmin())return;const rows=items.map(x=>({id:Number(x.id),payload:x,published:x.published!==false,updated_at:new Date().toISOString()}));if(rows.length){const up=await c.from('lx_catalog').upsert(rows,{onConflict:'id'});if(up.error)throw up.error;const ids=rows.map(x=>x.id);const {data:existing}=await c.from('lx_catalog').select('id');const remove=(existing||[]).map(x=>Number(x.id)).filter(id=>!ids.includes(id));if(remove.length)await c.from('lx_catalog').delete().in('id',remove)}else await c.from('lx_catalog').delete().gt('id',0);await refreshCatalog()}
async function saveUsers(items){const c=db();if(!c)return;const self=items.find(x=>String(x.id)===String(currentAuth?.id));if(self&&!isAdmin())await c.from('lx_profiles').update({name:self.name,ranking_visible:self.visible!==false,updated_at:new Date().toISOString()}).eq('user_id',currentAuth.id);if(isAdmin())for(const x of items.filter(z=>uuid(z.id))){await c.from('lx_profiles').update({name:x.name,verified:!!x.verified,ranking_visible:x.visible!==false,watched_hours:+x.watched||0,listened_hours:+x.listened||0,read_count:+x.read||0,streak:+x.streak||0,updated_at:new Date().toISOString()}).eq('user_id',x.id)}}
async function requestOrVote(r){const c=db();if(!c||!currentAuth)return;const {error}=await c.rpc('lx_request_or_vote',{p_kind:r.kind,p_media_type:r.mediaType,p_title:r.title,p_message:r.message||''});if(error)console.warn('LX request sync',error);await refreshRequests()}
async function refreshRequests(){const c=db();if(!c||!currentAuth)return;let q=c.from('lx_requests').select('id,owner_user_id,kind,media_type,title,message,votes,status,created_at,user_name').order('created_at',{ascending:false});const {data,error}=await q;if(error)return;const dir=new Map(adminDirectory.map(x=>[x.user_id,x]));const rows=(data||[]).map(r=>({id:Number(r.id),kind:r.kind,mediaType:r.media_type,title:r.title,message:r.message||'',votes:r.votes||1,status:r.status,created:+new Date(r.created_at),userEmail:isAdmin()?(dir.get(r.owner_user_id)?.email||''):currentAuth.email,userName:r.user_name||dir.get(r.owner_user_id)?.name||'Usuário',voters:isAdmin()?[]:[currentAuth.email]}));cache(S.keys.requests,rows)}
async function updateRequestStatus(id,status){const c=db();if(!c||!isAdmin())return;const {error}=await c.from('lx_requests').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await refreshRequests()}
async function publishNotices(items){const c=db();if(!c||!isAdmin())return;for(const n of items.slice(0,100)){if(String(n.id).includes('-'))continue;await c.from('lx_notifications').upsert({id:Number(n.id)||Date.now(),title:n.title,message:n.text||'',published:true,published_at:new Date().toISOString()},{onConflict:'id'})}await refreshNotices()}
async function setPremium(userId,plan,active=true){const c=db();if(!c||!isAdmin())throw new Error('ADMIN_REQUIRED');const until=active?new Date(Date.now()+(plan==='Anual'?365:30)*86400000).toISOString():null;const row={user_id:userId,plan:plan||'Mensal',active:!!active,status:active?'active':'inactive',current_period_end:until,updated_at:new Date().toISOString()};const {error}=await c.from('lx_subscriptions').upsert(row,{onConflict:'user_id'});if(error)throw error;await hydrateUser(currentAuth)}
async function refreshAnalytics(){const c=db();if(!c||!isAdmin())return;const {data,error}=await c.from('lx_analytics').select('event,data,created_at').order('created_at',{ascending:false}).limit(5000);if(!error)cache(S.keys.analytics,(data||[]).map(x=>({event:x.event,data:x.data||{},at:+new Date(x.created_at)})))}
async function track(event,data={}){const c=db();if(!c||!currentAuth)return;c.rpc('lx_track_event',{p_event:event,p_data:data||{}}).then(()=>{}).catch(()=>{})}
async function migrateLocalCatalog(){if(!isAdmin())throw new Error('ADMIN_REQUIRED');const source=S.read(S.keys.catalog,[]),items=typeof structuredClone==='function'?structuredClone(source):JSON.parse(JSON.stringify(source));let media=0,assets=0;
 const migrateKey=async(key,label)=>{if(!key||String(key).startsWith('cloud:'))return key;const blob=await S.getMedia(key).catch(()=>null);if(!blob)return key;media++;return uploadFile(label||key,blob,'media')};
 const migrateAsset=async(value,label)=>{if(!value||!String(value).startsWith('data:'))return value;const blob=await dataUriBlob(value);const k=await uploadFile(label,blob,'assets');assets++;return publicUrl(k.replace(/^cloud:/,''),cfg().assetBucket||'lx-assets')};
 for(const x of items){x.cover=await migrateAsset(x.cover,`cover_${x.id}`);x.banner=await migrateAsset(x.banner,`banner_${x.id}`);x.mediaKey=await migrateKey(x.mediaKey,`main_${x.id}`);x.trailerKey=await migrateKey(x.trailerKey,`trailer_${x.id}`);for(const e of x.episodes||[])e.mediaKey=await migrateKey(e.mediaKey,`episode_${x.id}_S${e.season||1}E${e.number||0}`);for(const t of x.tracks||[])t.mediaKey=await migrateKey(t.mediaKey,`track_${x.id}_${t.number||t.title||'audio'}`)}
 cache(S.keys.catalog,items);await saveCatalog(items);await publishNotices(S.read(S.keys.notices,[]));return {titles:items.length,media,assets}}
function status(){return {configured:enabled(),connected:!!client,user:currentAuth?.email||null,admin:isAdmin(),mediaBucket:cfg().mediaBucket||'lx-media',assetBucket:cfg().assetBucket||'lx-assets'}}
LX.cloud={enabled,db,user,profile,isAdmin,initPublic,signUp,signIn,resume,signOut,resetPassword,updatePassword,isRecoveryFlow,onLocalWrite,syncUserState,saveCatalog,saveUsers,saveBranding,requestOrVote,refreshRequests,updateRequestStatus,publishNotices,setPremium,track,uploadFile,publicUrl,mediaUrl,migrateLocalCatalog,status,hydrateUser,refreshBranding};
})();
