(()=>{const LX=window.LX,S=LX.store,$=id=>document.getElementById(id);
const P=['poster-matrix.webp','poster-johnwick.webp','poster-jjk.webp','poster-doramas.webp','poster-vikings.webp','poster-breaking.webp','poster-suits.webp','poster-naruto.webp','poster-onepiece.webp','poster-demonslayer.webp','poster-attack.webp','poster-boys.webp','poster-stranger.webp','poster-dragonball.webp','poster-lastofus.webp','poster-wednesday.webp','poster-spiderman.webp','poster-casa.webp'].map(x=>'assets/'+x);
const DEMO=[
{id:101,title:'Código Infinito',type:'Filme',year:2026,rating:'14',genre:'Ficção',desc:'Uma descoberta muda a maneira como uma cidade inteira percebe o tempo.',cover:P[0],banner:P[1],featured:true,trending:true,newRelease:true,published:true,progress:36,duration:'2h 08min',director:'L. Martins',cast:['Maya Rocha','Caio Luz'],languages:['Português','English'],subtitles:['Português','English'],intro:82,tags:['tecnologia','tempo','cidade']},
{id:102,title:'Cidade Zero',type:'Série',year:2026,rating:'16',genre:'Suspense',desc:'Segredos e tecnologia se cruzam em uma cidade que nunca desliga.',cover:P[5],banner:P[12],featured:true,trending:true,newRelease:true,published:true,progress:62,creator:'N. Costa',cast:['Luna Vale','Ravi Nunes'],tags:['mistério','tecnologia'],episodes:[{season:1,number:1,title:'Ponto de partida',duration:'48min',intro:74},{season:1,number:2,title:'Sinal perdido',duration:'51min',intro:78},{season:1,number:3,title:'Cidade fantasma',duration:'53min',intro:80}]},
{id:103,title:'Lâmina Celeste',type:'Anime',year:2026,rating:'12',genre:'Aventura',desc:'Um mapa que muda todas as noites leva um jovem para além do céu.',cover:P[2],banner:P[9],featured:true,trending:true,newRelease:true,published:true,progress:20,studio:'Studio LX',tags:['aventura','fantasia'],episodes:[{season:1,number:1,title:'O mapa azul',duration:'24min',intro:91},{season:1,number:2,title:'Entre nuvens',duration:'24min',intro:89},{season:1,number:3,title:'A lâmina',duration:'24min',intro:92}]},
{id:104,title:'Seul Depois das Onze',type:'Dorama',year:2026,rating:'12',genre:'Romance',desc:'Dois desconhecidos se encontram no mesmo ônibus, sempre depois das onze.',cover:P[3],banner:P[15],featured:false,trending:true,newRelease:true,published:true,progress:0,cast:['Min Seo','Ji Han'],tags:['romance','seul'],episodes:[{season:1,number:1,title:'Último ônibus',duration:'58min'},{season:1,number:2,title:'Onze e quinze',duration:'61min'}]},
{id:105,title:'Arquivo Aurora',type:'Livro',year:2026,rating:'14',genre:'Mistério',desc:'Documentos encontrados em uma estação polar revelam uma história que deveria permanecer congelada.',cover:P[14],banner:P[17],featured:true,trending:true,newRelease:true,published:true,progress:48,author:'Clara Monte',isbn:'978-00-00000-00-1',tags:['mistério','polar'],chapters:[{title:'Capítulo 1 — O gelo',text:'A estação Aurora não aparecia em nenhum mapa. Ainda assim, às três e dezessete da manhã, o rádio captou uma voz que repetia as mesmas quatro palavras. Ninguém deveria estar lá. A equipe abriu o primeiro arquivo e encontrou uma fotografia datada de vinte anos no futuro.'},{title:'Capítulo 2 — O arquivo',text:'O documento seguinte não tinha assinatura. Havia apenas coordenadas, nomes riscados e uma instrução: não abrir a porta norte. Quando o gerador falhou, alguém bateu três vezes do outro lado.'},{title:'Capítulo 3 — Luz branca',text:'Ao amanhecer, uma faixa de luz cruzou o horizonte. Não era aurora. O sensor registrou calor onde só deveria haver gelo.'}]},
{id:106,title:'As Quatro Luas',type:'Livro',year:2025,rating:'12',genre:'Fantasia',desc:'Quatro luas, quatro reinos e uma noite capaz de mudar todos eles.',cover:P[4],banner:P[6],featured:false,trending:false,newRelease:false,published:true,author:'Ravi Nunes',tags:['fantasia','reinos'],chapters:[{title:'Prólogo',text:'Na noite em que a quarta lua apareceu, os sinos tocaram sem que ninguém os tocasse.'},{title:'A primeira ponte',text:'Lina atravessou a ponte antes do amanhecer. Do outro lado, o reino não era o mesmo.'}]},
{id:107,title:'Vértice',type:'Música',year:2026,rating:'L',genre:'Pop eletrônico',desc:'Um álbum noturno entre sintetizadores e luzes da cidade.',cover:P[11],banner:P[13],featured:true,trending:true,newRelease:true,published:true,artist:'NOVA LX',album:'Vértice',tags:['pop','eletrônico'],tracks:[{title:'Neon',duration:214},{title:'Vértice',duration:196},{title:'Zero Gravity',duration:238},{title:'Afterglow',duration:205}]},
{id:108,title:'Pulso',type:'Música',year:2026,rating:'L',genre:'R&B',desc:'Graves profundos e uma madrugada que não termina.',cover:P[7],banner:P[8],featured:false,trending:true,newRelease:true,published:true,artist:'MAYA',album:'Pulso',tags:['r&b','noturno'],tracks:[{title:'Pulso',duration:188},{title:'Luz Baixa',duration:202},{title:'Sem Pressa',duration:219}]},
{id:109,title:'Horizonte Vermelho',type:'Filme',year:2025,rating:'16',genre:'Ação',desc:'Um resgate impossível atravessa uma cidade em colapso.',cover:P[6],banner:P[16],featured:false,trending:true,newRelease:false,published:true,progress:74,duration:'1h 54min',director:'C. Avelar',tags:['ação','resgate']},
{id:110,title:'Código Zero',type:'Série',year:2026,rating:'14',genre:'Tecnologia',desc:'Uma falha global conecta pessoas que nunca deveriam ter se conhecido.',cover:P[17],banner:P[0],featured:false,trending:false,newRelease:true,published:true,creator:'R. Silva',tags:['tecnologia','falha'],episodes:[{season:1,number:1,title:'Falha',duration:'47min'},{season:1,number:2,title:'Eco',duration:'49min'}]}
];
const DEMO_USERS=[{id:1,name:'Sergio LX',email:'sergio@lxplus.demo',verified:true,visible:true,watched:118,listened:74,read:9,streak:18},{id:2,name:'Maya',email:'maya@lxplus.demo',verified:true,visible:true,watched:96,listened:129,read:4,streak:12},{id:3,name:'Caio',email:'caio@lxplus.demo',verified:false,visible:true,watched:142,listened:31,read:2,streak:7},{id:4,name:'Luna',email:'luna@lxplus.demo',verified:false,visible:true,watched:83,listened:61,read:14,streak:22},{id:5,name:'Noah',email:'noah@lxplus.demo',verified:true,visible:true,watched:65,listened:151,read:1,streak:9}];
const DEFAULT_NOTICES=[{id:1,title:'Novo episódio disponível',text:'Cidade Zero · Episódio 3 já está na LX Plus.',time:'Agora',read:false},{id:2,title:'Nova recomendação',text:'Selecionamos Lâmina Celeste para você.',time:'2h',read:false},{id:3,title:'Ranking LX',text:'Você subiu posições no ranking mensal.',time:'Hoje',read:false}];
function seed(){
 if(LX.cloud?.enabled?.()){
  if(!S.read(S.keys.catalog,null))S.writeLocal(S.keys.catalog,DEMO);
  if(!S.read(S.keys.users,null))S.writeLocal(S.keys.users,[]);
  if(!S.read(S.keys.notices,null))S.writeLocal(S.keys.notices,[]);
 }else{
  if(!S.read(S.keys.catalog,null))S.writeLocal(S.keys.catalog,DEMO);
  if(!S.read(S.keys.users,null))S.writeLocal(S.keys.users,DEMO_USERS);
  if(!S.read(S.keys.notices,null))S.writeLocal(S.keys.notices,DEFAULT_NOTICES)
 }
 if(!S.read(S.keys.globalBranding,null))S.writeLocal(S.keys.globalBranding,{splashEyebrow:'DIGITAL MEDIA EXPERIENCE',splashTag:'DM VERSION',splashTitle:'Seu entretenimento. Do seu jeito.',splashSubtitle:'Filmes, séries, animes, doramas, livros e música conectados por uma única experiência.',accent:'#42a5ff',featuredIds:[]});if(!S.read(S.keys.analytics,null))S.writeLocal(S.keys.analytics,[]);if(!S.read(S.keys.requests,null))S.writeLocal(S.keys.requests,[]);if(!S.read(S.keys.ratings,null))S.writeLocal(S.keys.ratings,{});if(!S.read(S.keys.preferences,null))S.writeLocal(S.keys.preferences,{});if(!S.read(S.keys.subscriptions,null))S.writeLocal(S.keys.subscriptions,{})
}
const catalog=()=>S.read(S.keys.catalog,DEMO),users=()=>S.read(S.keys.users,LX.cloud?.enabled?.()?[]:DEMO_USERS),notices=()=>S.read(S.keys.notices,LX.cloud?.enabled?.()?[]:DEFAULT_NOTICES),requests=()=>S.read(S.keys.requests,[]),ratings=()=>S.read(S.keys.ratings,{}),history=()=>S.read(S.keys.history,{}),myList=()=>S.read(S.keys.list,[]),preferences=()=>S.read(S.keys.preferences,{}),subscriptions=()=>S.read(S.keys.subscriptions,{}),branding=()=>S.read(S.keys.globalBranding,{splashEyebrow:'DIGITAL MEDIA EXPERIENCE',splashTag:'DM VERSION',splashTitle:'Seu entretenimento. Do seu jeito.',splashSubtitle:'Filmes, séries, animes, doramas, livros e música conectados por uma única experiência.',accent:'#42a5ff',featuredIds:[]});
const saveCatalog=x=>{S.writeLocal(S.keys.catalog,x);LX.cloud?.saveCatalog?.(x).catch(e=>{console.warn(e);LX.toast?.('Falha ao sincronizar catálogo com a nuvem.')})},saveUsers=x=>{S.writeLocal(S.keys.users,x);LX.cloud?.saveUsers?.(x).catch(e=>console.warn(e))},saveRequests=x=>S.writeLocal(S.keys.requests,x),saveRatings=x=>S.write(S.keys.ratings,x),savePreferences=x=>S.write(S.keys.preferences,x),saveSubscriptions=x=>S.writeLocal(S.keys.subscriptions,x),saveBranding=async x=>{S.writeLocal(S.keys.globalBranding,x);if(LX.cloud?.enabled?.())await LX.cloud.saveBranding(x);return x};
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function levenshtein(a,b){a=normalize(a);b=normalize(b);const m=Array.from({length:b.length+1},(_,i)=>[i]);for(let j=0;j<=a.length;j++)m[0][j]=j;for(let i=1;i<=b.length;i++)for(let j=1;j<=a.length;j++)m[i][j]=b[i-1]===a[j-1]?m[i-1][j-1]:1+Math.min(m[i-1][j],m[i][j-1],m[i-1][j-1]);return m[b.length][a.length]}
function searchable(x){return [x.title,x.genre,x.type,x.artist,x.album,x.author,x.director,x.creator,x.studio,...(x.cast||[]),...(x.tags||[])].filter(Boolean).join(' ')}
function search(items,q){q=normalize(q);if(!q)return items;const terms=q.split(/\s+/);return items.map(x=>{const hay=normalize(searchable(x));let score=terms.reduce((s,t)=>s+(hay.includes(t)?5:0),0);score+=normalize(x.title).includes(q)?20:0;const d=levenshtein(x.title,q);score+=Math.max(0,8-d);return {x,score}}).filter(z=>z.score>0).sort((a,b)=>b.score-a.score).map(z=>z.x)}
function quality(x){
 const checks=[],req=(label,ok)=>checks.push({label,ok:!!ok});
 req('Título',x.title);req('Tipo',x.type);req('Gênero',x.genre);req('Ano',x.year);req('Classificação',x.rating);req('Capa',x.cover);
 if(x.type==='Filme'){req('Descrição',x.desc&&x.desc.length>=20);req('Banner',x.banner);req('Diretor',x.director);req('Duração',x.duration);req('Vídeo / HLS',x.mediaKey||x.demoMedia||x.hlsUrl||Object.keys(x.qualitySources||{}).length)}
 if(['Série','Anime','Dorama'].includes(x.type)){req('Descrição',x.desc&&x.desc.length>=20);req('Banner',x.banner);req(x.type==='Anime'?'Estúdio':'Criador/produção',x.type==='Anime'?x.studio:x.creator);req('Episódios',x.episodes?.length);req('Numeração válida',x.episodes?.every(e=>e.number&&e.season));req('Mídia dos episódios',x.episodes?.every(e=>e.mediaKey||e.hlsUrl||Object.keys(e.qualitySources||{}).length))}
 if(x.type==='Livro'){req('Descrição',x.desc&&x.desc.length>=20);req('Autor',x.author);req('Arquivo/capítulos',x.mediaKey||x.chapters?.length)}
 if(x.type==='Música'){req('Artista',x.artist);req('Descrição ou letra',(x.desc&&x.desc.length>=10)||(x.lyrics&&x.lyrics.length>=10));req('Arquivo/faixas',x.mediaKey||x.tracks?.length)}
 const pass=checks.filter(c=>c.ok).length;return {score:Math.round(pass/checks.length*100),checks,pass,total:checks.length,ready:pass===checks.length}
}
function recommendation(items,hist,ratingsMap,pref={}){const opened=Object.keys(hist).map(Number),recent=items.filter(x=>opened.includes(x.id)).sort((a,b)=>(hist[b.id]?.opened||0)-(hist[a.id]?.opened||0));const genres=new Map(),types=new Map(),tags=new Map();recent.slice(0,12).forEach(x=>{genres.set(x.genre,(genres.get(x.genre)||0)+3);types.set(x.type,(types.get(x.type)||0)+1);(x.tags||[]).forEach(t=>tags.set(t,(tags.get(t)||0)+2))});const fav=new Set((pref.genres||[]).map(normalize));return items.map(x=>{let s=(genres.get(x.genre)||0)+(types.get(x.type)||0)+(x.trending?1:0)+(x.newRelease?1:0);if(fav.has(normalize(x.genre)))s+=7;(x.tags||[]).forEach(t=>s+=tags.get(t)||0);const r=ratingsMap[x.id];if(r)s+=r>=4?4:r<=2?-3:0;if(opened.includes(x.id))s-=2;return {x,s}}).sort((a,b)=>b.s-a.s).map(z=>z.x)}
function track(event,data={}){const a=S.read(S.keys.analytics,[]);a.push({event,data,at:Date.now()});if(a.length>1000)a.splice(0,a.length-1000);S.writeLocal(S.keys.analytics,a);LX.cloud?.track?.(event,data)}
function analytics(){return S.read(S.keys.analytics,[])}
function requestKey(r){return normalize(`${r.kind}|${r.mediaType}|${r.title}`)}
function addOrVoteRequest(r){const arr=requests(),k=requestKey(r),found=arr.find(x=>requestKey(x)===k&&!['Concluído','Fechado'].includes(x.status));let out;if(found){found.votes=(found.votes||1)+1;found.voters=[...(found.voters||[]),r.userEmail].filter((x,i,a)=>a.indexOf(x)===i);found.updated=Date.now();out={merged:true,item:found}}else{r.votes=1;r.voters=[r.userEmail];arr.unshift(r);out={merged:false,item:r}}saveRequests(arr);LX.cloud?.requestOrVote?.(r);return out}
async function hash(s){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function api(path,opts={}){if(!LX.config.apiBase)throw new Error('API_NOT_CONFIGURED');const r=await fetch(LX.config.apiBase+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`HTTP_${r.status}`);return r.json()}
const auth={
 async login(email,password){if(LX.cloud?.enabled?.())return LX.cloud.signIn(email,password);if(LX.config.apiBase)return api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});const demoAllowed=location.protocol==='file:'||['localhost','127.0.0.1'].includes(location.hostname),adm=LX.config.localDemoAdmin;if(demoAllowed&&email===adm.email&&password===adm.password)return {user:{name:'Administrador',email,admin:true}};if(LX.config.production&&LX.config.requireCloudInProduction!==false)throw new Error('CLOUD_NOT_CONFIGURED');const a=S.read(S.keys.accounts,[]).find(x=>x.email===email);if(!a||a.pass!==await hash(password))throw new Error('INVALID_CREDENTIALS');return {user:a}},
 async register({name,email,password,ranking}){if(LX.cloud?.enabled?.())return LX.cloud.signUp({name,email,password,ranking});if(LX.config.apiBase)return api('/api/auth/register',{method:'POST',body:JSON.stringify({name,email,password,ranking})});const demoAllowed=location.protocol==='file:'||['localhost','127.0.0.1'].includes(location.hostname);if(LX.config.production&&LX.config.requireCloudInProduction!==false&&!demoAllowed)throw new Error('CLOUD_NOT_CONFIGURED');let a=S.read(S.keys.accounts,[]);if(a.some(x=>x.email===email)||email===LX.config.localDemoAdmin.email)throw new Error('EMAIL_EXISTS');const user={id:Date.now(),name,email,pass:await hash(password),ranking,created:new Date().toISOString()};a.push(user);S.write(S.keys.accounts,a);const u=users();u.push({id:user.id,name,email,verified:false,visible:ranking,watched:0,listened:0,read:0,streak:1});saveUsers(u);return {user}},
 async resume(){return LX.cloud?.enabled?.()?LX.cloud.resume():null},
 async logout(){if(LX.cloud?.enabled?.())await LX.cloud.signOut()},
 async resetPassword(email){if(LX.cloud?.enabled?.())return LX.cloud.resetPassword(email);throw new Error('CLOUD_NOT_CONFIGURED')},
 async updatePassword(password){if(LX.cloud?.enabled?.())return LX.cloud.updatePassword(password);throw new Error('CLOUD_NOT_CONFIGURED')}
};
LX.data={P,DEMO,seed,catalog,users,notices,requests,ratings,history,myList,preferences,subscriptions,branding,saveCatalog,saveUsers,saveRequests,saveRatings,savePreferences,saveSubscriptions,saveBranding,search,quality,recommendation,track,analytics,addOrVoteRequest,auth,normalize,cloud:LX.cloud};})();
