(()=>{const LX=window.LX;const PREFIX='lx16_';
const keys={accounts:'accounts',users:'users',catalog:'catalog',session:'session',history:'history',list:'list',theme:'theme',accent:'accent',notices:'notices',requests:'requests',ratings:'ratings',analytics:'analytics',publicLists:'publicLists',noticeReads:'noticeReads',preferences:'preferences',subscriptions:'subscriptions',profileStyles:'profileStyles',layoutMode:'layoutMode',motion:'motion',playerPrefs:'playerPrefs',globalBranding:'globalBranding'};
const read=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(PREFIX+k));return x??d}catch{return d}};
const writeLocal=(k,v)=>localStorage.setItem(PREFIX+k,JSON.stringify(v));
const write=(k,v)=>{writeLocal(k,v);queueMicrotask(()=>LX.cloud?.onLocalWrite?.(k,v))};
let dbp;function db(){if(!dbp)dbp=new Promise((res,rej)=>{const r=indexedDB.open('LXPlus16Media',1);r.onupgradeneeded=()=>r.result.createObjectStore('media');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
async function putMedia(key,blob){if(LX.cloud?.enabled?.())return LX.cloud.uploadFile(key,blob,'media');const d=await db();return new Promise((res,rej)=>{const tx=d.transaction('media','readwrite');tx.objectStore('media').put(blob,key);tx.oncomplete=()=>res(key);tx.onerror=()=>rej(tx.error)})}
async function getMedia(key){if(!key)return null;if(String(key).startsWith('cloud:'))return await LX.cloud?.mediaUrl?.(String(key).slice(6))||null;const d=await db();return new Promise((res,rej)=>{const r=d.transaction('media').objectStore('media').get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function putAsset(key,file,folder='assets'){if(LX.cloud?.enabled?.()){const mediaKey=await LX.cloud.uploadFile(key,file,folder);return LX.cloud.publicUrl(String(mediaKey).replace(/^cloud:/,''),LX.config.supabase?.assetBucket||'lx-assets')}return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
LX.store={keys,read,write,writeLocal,putMedia,getMedia,putAsset,reset(){Object.values(keys).forEach(k=>localStorage.removeItem(PREFIX+k))}}})();
