(()=>{const LX=window.LX,D=LX.data,S=LX.store,$=id=>document.getElementById(id),$$=s=>Array.from(document.querySelectorAll(s));
const state=LX.state={screen:'splash',mode:'Assistir',category:'Início',query:'',user:null,profile:null,hero:0,heroTimer:null,musicQueue:[],musicIndex:0,rankingPeriod:'Mensal',rankingKind:'Geral',readerSize:20,readerPaper:false,libraryType:'Todos'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));LX.esc=esc;
const show=id=>{['splash','auth','profiles','app','admin'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden');state.screen=id};LX.show=show;
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2300)};LX.toast=toast;
const initials=n=>(n||'LX').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();LX.initials=initials;
const greeting=()=>new Date().getHours()<12?'Bom dia':new Date().getHours()<18?'Boa tarde':'Boa noite';
const verifiedBadge=(size='sm')=>`<span class="verified-badge verified-${size}" aria-label="Verificado" title="Conta verificada"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path class="seal" d="M12 1.9l2.1 1 2.45-.23 1.55 1.71 2.32.77.67 2.36 1.58 1.87-.47 2.38.96 2.27-1.16 2.13.07 2.44-1.95 1.46-.83 2.29-2.42.45-1.82 1.63-2.41-.56-2.2 1.04-2.2-1.04-2.41.56-1.82-1.63-2.42-.45-.83-2.29-1.95-1.46.07-2.44-1.16-2.13.96-2.27-.47-2.38 1.58-1.87.67-2.36 2.32-.77 1.55-1.71 2.45.23z"/><path class="check" d="M7.2 12.4l3 3.1 6.8-6.7"/></svg></span>`;LX.verifiedBadge=verifiedBadge;const verified=(n,v,size='sm')=>`${esc(n)}${v?verifiedBadge(size):''}`;LX.verified=verified;
const fmt=s=>{s=Math.floor(+s||0);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};LX.fmt=fmt;

const PROFILE_PRESETS={
  lx:{label:'LX',mark:'LX',bg:'linear-gradient(145deg,#173e70,#1184f4)'},
  plus:{label:'Plus',mark:'+',bg:'linear-gradient(145deg,#5530a8,#9b63ff)'},
  crown:{label:'Coroa',mark:'♛',bg:'linear-gradient(145deg,#6a4810,#e0a329)'},
  play:{label:'Play',mark:'▶',bg:'linear-gradient(145deg,#5a1924,#e24d62)'},
  music:{label:'Música',mark:'♫',bg:'linear-gradient(145deg,#18354e,#20a3c8)'},
  book:{label:'Livro',mark:'▤',bg:'linear-gradient(145deg,#174335,#36b985)'},
  neon:{label:'Neon',mark:'LX',bg:'linear-gradient(145deg,#10131d,#174a77)',glow:true},
  mono:{label:'Mono',mark:'LX',bg:'linear-gradient(145deg,#191919,#454545)'},
  owl:{label:'Coruja',mark:'🦉',bg:'linear-gradient(145deg,#32261b,#7b5a36)'},
  shield:{label:'Shield',mark:'⬢',bg:'linear-gradient(145deg,#112f4c,#1d8bcf)'},
  star:{label:'Star',mark:'✦',bg:'linear-gradient(145deg,#37246b,#9360ff)'},
  flame:{label:'Flame',mark:'✶',bg:'linear-gradient(145deg,#4a1d15,#ff7b49)'}
};LX.PROFILE_PRESETS=PROFILE_PRESETS;
const avatarArt=(skin,hair,shirt,bg1,bg2)=>`data:image/svg+xml;utf8,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96'><defs><linearGradient id='g' x1='0' x2='1' y1='0' y2='1'><stop offset='0' stop-color='${bg1}'/><stop offset='1' stop-color='${bg2}'/></linearGradient></defs><rect width='96' height='96' rx='22' fill='url(#g)'/><circle cx='48' cy='35' r='18' fill='${skin}'/><path d='M30 32c2-12 11-20 21-20 9 0 18 5 22 18-5-4-11-6-17-6-9 0-15 4-26 8z' fill='${hair}'/><circle cx='41' cy='36' r='2' fill='#1f2730'/><circle cx='55' cy='36' r='2' fill='#1f2730'/><path d='M42 45c4 4 8 4 12 0' stroke='#874d4d' stroke-width='2.3' fill='none' stroke-linecap='round'/><path d='M24 91c2-18 14-28 24-28s22 10 24 28' fill='${shirt}'/><path d='M35 61c4 4 8 6 13 6s10-2 14-6' stroke='rgba(255,255,255,.4)' stroke-width='2' fill='none'/></svg>`)}`;
const PROFILE_GALLERY=[
  {label:'Alex',url:avatarArt('#f3c9a7','#2a2f42','#3b82f6','#0b1629','#183d74')},
  {label:'Maya',url:avatarArt('#f0c1a1','#241a17','#ff6b8a','#2b1023','#5a1c34')},
  {label:'Noah',url:avatarArt('#e8bf98','#4d3026','#20b486','#112824','#1f5a48')},
  {label:'Luna',url:avatarArt('#efc8ae','#3a2038','#8b7cff','#1b1637','#4f3db1')},
  {label:'Caio',url:avatarArt('#c98d62','#1c1a20','#4cc9f0','#091929','#0d5772')},
  {label:'Sora',url:avatarArt('#f5d3ba','#70502d','#ffb347','#2d1c11','#7a441c')},
  {label:'Iris',url:avatarArt('#d39a73','#1b263b','#39d99f','#0f1f25','#1b5b46')},
  {label:'Theo',url:avatarArt('#f3d0b1','#2b2b2b','#e95c5c','#281417','#5e1d28')},
  {label:'Zoe',url:avatarArt('#f2c7a6','#2f2347','#7c5cff','#131027','#40329b')},
  {label:'Nina',url:avatarArt('#efc09f','#362015','#ff8f66','#22120d','#79321b')},
  {label:'Kai',url:avatarArt('#c88d67','#0f1b2d','#58b5ff','#081420','#14436f')},
  {label:'Milo',url:avatarArt('#efcfb1','#263520','#8ed65b','#121d10','#355827')}
];LX.PROFILE_GALLERY=PROFILE_GALLERY;
function profileStyle(email=''){const all=S.read(S.keys.profileStyles,{});return all[email]||{preset:'lx'}}
function avatarHTML(name,email='',cls='profile-avatar'){const st=profileStyle(email),shape=st.shape||'rounded',premium=!!D.subscriptions?.()?.[email]?.active,frame=premium?(st.frame||'none'):'none',classes=`${cls} avatar-shape-${shape} avatar-frame-${frame}`;if(st.image)return `<div class="${classes} avatar-image" style="background-image:url('${st.image.replace(/'/g,'%27')}')"></div>`;const pr=PROFILE_PRESETS[st.preset]||PROFILE_PRESETS.lx;return `<div class="${classes} ${pr.glow?'avatar-glow':''}" style="background:${pr.bg}">${esc(pr.mark||initials(name))}</div>`}
LX.profileStyle=profileStyle;LX.avatarHTML=avatarHTML;

function posterWalls(){const arr=[...D.P,...D.P,...D.P];$('wallA').innerHTML=arr.map(x=>`<div class="poster-tile" style="background-image:url('${x}')"></div>`).join('');$('wallB').innerHTML=[...arr].reverse().map(x=>`<div class="poster-tile" style="background-image:url('${x}')"></div>`).join('')}
function authTab(t){$('tabLogin').classList.toggle('active',t==='login');$('tabRegister').classList.toggle('active',t==='register');$('loginForm').classList.toggle('hidden',t!=='login');$('registerForm').classList.toggle('hidden',t!=='register')}
function renderProfiles(){const n=state.user?.name||'Usuário',email=state.user?.email||'',u=D.users().find(x=>x.email===email)||state.user||{},st=profileStyle(email),sub=D.subscriptions()[email];$('profileGrid').innerHTML=`<button class="profile-card profile-card-v25" data-profile="main">${avatarHTML(n,email,'profile-avatar')}<strong>${verified(n,u.verified,'sm')}</strong><small>${esc(st.bio||'Perfil principal')}</small>${sub?.active?'<span class="premium-user-pill">PREMIUM</span>':''}</button><button class="profile-card profile-card-v25" data-profile="kids"><div class="profile-avatar kids-avatar avatar-shape-rounded">K</div><strong>Kids</strong><small>Conteúdo infantil</small></button>`;$$('[data-profile]').forEach(b=>b.onclick=()=>{state.profile={id:b.dataset.profile,name:b.dataset.profile==='kids'?'Kids':n,kids:b.dataset.profile==='kids'};$('profileBtn').innerHTML=b.dataset.profile==='kids'?'<span>K</span>':avatarHTML(n,email,'avatar-inline');renderApp();show('app')})}
function categories(){return state.mode==='Assistir'?['Início','Filmes','Séries','Animes','Doramas','Minha Lista','Pedidos','Ranking LX']:state.mode==='Ler'?['Início','Livros','Minha Lista','Pedidos','Ranking LX']:['Início','Música','Minha Lista','Pedidos','Ranking LX']}
function renderCategories(){$('categoryNav').innerHTML=categories().map(c=>`<button class="${c===state.category?'active':''}" data-cat="${c}">${c}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{const c=b.dataset.cat;if(c==='Ranking LX')return LX.openRanking();if(c==='Pedidos')return LX.openRequests();state.category=c;renderApp()})}
function allowed(){return state.mode==='Assistir'?['Filme','Série','Anime','Dorama']:state.mode==='Ler'?['Livro']:['Música']}
function items(){const now=Date.now();let a=D.catalog().filter(x=>x.published!==false&&(!x.scheduledAt||+new Date(x.scheduledAt)<=now)&&allowed().includes(x.type));if(state.profile?.kids)a=a.filter(x=>!['16','18'].includes(String(x.rating)));if(state.category==='Minha Lista')a=a.filter(x=>D.myList().includes(x.id));else if(state.category!=='Início'){const map={Filmes:'Filme',Séries:'Série',Animes:'Anime',Doramas:'Dorama',Livros:'Livro',Música:'Música'};if(map[state.category])a=a.filter(x=>x.type===map[state.category])}if(state.query)a=D.search(a,state.query);return a.sort((x,y)=>(+(y.priority||0))-(+(x.priority||0))||((+new Date(y.publishedAt||y.createdAt||0))-(+new Date(x.publishedAt||x.createdAt||0))))}
function renderHero(){const branding=D.branding?.()||{},preferred=(branding.featuredIds||[]).map(Number);let f=items().filter(x=>preferred.includes(x.id));if(!f.length)f=items().filter(x=>x.featured);if(!f.length)f=items().slice(0,4);if(!f.length){$('hero').innerHTML='';return}state.hero=Math.min(state.hero,f.length-1);$('hero').innerHTML=f.map((x,i)=>`<article class="hero-slide ${i===state.hero?'active':''}"><div class="hero-bg" style="background-image:url('${x.banner||x.cover}')"></div><div class="hero-copy"><span class="eyebrow">${state.mode.toUpperCase()} · LX SELECT</span><h1>${esc(x.title)}</h1><div class="hero-meta"><span>${x.year}</span><span>${esc(x.rating)}</span><span>${esc(x.genre)}</span><span>${esc(x.type)}</span></div><p>${esc(x.desc)}</p><div class="hero-actions"><button class="primary-btn" onclick="LX.primary(${x.id})">${x.type==='Livro'?'▤ Ler agora':x.type==='Música'?'♫ Ouvir':'▶ Assistir'}</button><button class="secondary-btn" onclick="LX.detail(${x.id})">ⓘ Mais informações</button></div></div></article>`).join('')+`<div class="hero-dots">${f.map((_,i)=>`<button class="${i===state.hero?'active':''}" data-dot="${i}"></button>`).join('')}</div>`;$$('[data-dot]').forEach(d=>d.onclick=()=>{state.hero=+d.dataset.dot;renderHero();heroTimer(f.length)});heroTimer(f.length)}
function heroTimer(n){clearInterval(state.heroTimer);if(n>1)state.heroTimer=setInterval(()=>{state.hero=(state.hero+1)%n;renderHero()},7600)}
function renderWelcome(){const h=D.history(),entries=Object.values(h).filter(Boolean),sub=D.subscriptions()[state.user?.email||''],email=state.user?.email||'',u=D.users().find(x=>x.email===email)||state.user||{},layout=S.read(S.keys.layoutMode,'cinema'),theme=S.read(S.keys.theme,'dark'),prefs=D.preferences()[email]||{};$('welcome').innerHTML=`<div class="welcome-card welcome-v24"><div class="welcome-user">${avatarHTML(state.profile?.name||state.user?.name||'LX',email,'welcome-avatar')}<div><span class="eyebrow">${state.mode.toUpperCase()} ${sub?.active?'<span class="premium-user-pill">PREMIUM</span>':''}</span><h2>${greeting()}, <span>${esc(state.profile?.name||state.user?.name||'você')}</span> ${u.verified?LX.verifiedBadge('md'):''}</h2><p>${state.mode==='Assistir'?'Continue suas histórias ou descubra algo novo.':state.mode==='Ler'?'Retome sua leitura ou abra um novo universo.':'Sua trilha continua exatamente de onde parou.'}</p></div></div><div class="mode-summary"><div><strong>${entries.length}</strong><small>EM PROGRESSO</small></div><div><strong>${D.myList().length}</strong><small>MINHA LISTA</small></div><div><strong>${items().length}</strong><small>NO CATÁLOGO</small></div></div></div><div class="experience-strip"><div><span>◎</span><strong>${layout==='app'?'Modo App':layout==='compact'?'Compacto':'Cinema'}</strong><small>Interface</small></div><div><span>◐</span><strong>${theme==='light'?'Claro':'Escuro'}</strong><small>Tema</small></div><div><span>✦</span><strong>${prefs.genres?.length||0}</strong><small>Preferências</small></div><div><span>☁</span><strong>${LX.cloud?.enabled?.()?'Online':'Local'}</strong><small>Sincronização</small></div></div>`}
function card(x,progress,rank){const h=D.history()[x.id],p=h?.progress??x.progress??0,r=D.ratings()[x.id],listed=D.myList().includes(x.id);return `<article class="card" onclick="LX.detail(${x.id})"><div class="card-art" style="background-image:url('${x.cover||x.banner}')"><div class="card-badges">${rank?`<span>#${rank}</span>`:''}${x.newRelease?'<span>NOVO</span>':''}${r?`<span>★ ${r}</span>`:''}${listed?'<span>✓ LISTA</span>':''}</div><div class="card-copy"><div class="card-title">${esc(x.title)}</div><div class="card-meta">${x.year} · ${esc(x.type)} · ${esc(x.genre)}</div></div>${progress&&p?`<div class="progress-line"><i style="width:${Math.min(100,p)}%"></i></div>`:''}</div></article>`}
function rail(title,sub,a,progress=false,top10=false){if(!a.length)return'';const id='r'+Math.random().toString(36).slice(2,8);return `<section class="rail-section"><div class="rail-head"><div><h2>${title}</h2><p>${sub}</p></div><span>${a.length} títulos</span></div><div class="rail-wrap"><button class="rail-arrow left" onclick="LX.scroll('${id}',-1)">‹</button><div class="rail" id="${id}">${a.map((x,i)=>card(x,progress,top10?i+1:null)).join('')}</div><button class="rail-arrow right" onclick="LX.scroll('${id}',1)">‹</button></div></section>`}
function renderHome(){const a=items();if(state.query){$('homeContent').innerHTML=rail(`Resultados para “${esc(state.query)}”`,'Busca tolerante a erros por título, elenco, autor, artista, gênero e tags.',a);return}if(state.category!=='Início'){$('homeContent').innerHTML=rail(state.category,'Tudo nesta categoria.',a);return}const h=D.history(),pref=D.preferences()[state.user?.email||'']||{},histEntries=Object.entries(h).filter(([,v])=>v?.opened).sort((a,b)=>(b[1].opened||0)-(a[1].opened||0)),recentId=histEntries[0]?.[0],recent=D.catalog().find(x=>String(x.id)===String(recentId)),cont=a.filter(x=>h[x.id]?.progress>0&&h[x.id]?.progress<98),recs=D.recommendation(a,h,D.ratings(),pref).slice(0,12),because=recent?a.filter(x=>x.id!==recent.id&&(x.genre===recent.genre||x.type===recent.type)&&!h[x.id]).slice(0,10):[],top=[...a].sort((x,y)=>(y.trending?1:0)-(x.trending?1:0)||(+y.priority||0)-(+x.priority||0)).slice(0,10),newest=[...a].sort((x,y)=>(+new Date(y.publishedAt||y.createdAt||0))-(+new Date(x.publishedAt||x.createdAt||0))).slice(0,12);let html='';if(cont.length)html+=rail(state.mode==='Ler'?'Continuar lendo':state.mode==='Ouvir'?'Ouvir novamente':'Continuar assistindo','Retome exatamente do segundo em que parou.',cont,true);if(recs.length){const why=pref.genres?.length?`Preferências: ${pref.genres.slice(0,3).join(', ')}. Também usamos histórico, notas e tags.`:'Baseado no seu histórico, avaliações, gêneros e tags. Você pode ajustar isso no Perfil.';html+=rail('Recomendado para você',why,recs)}if(because.length)html+=rail(`Porque você ${recent.type==='Livro'?'leu':recent.type==='Música'?'ouviu':'assistiu'} ${esc(recent.title)}`,'Uma seleção relacionada ao seu histórico recente.',because);html+=rail('Top 10 LX','Os títulos mais fortes neste momento.',top,false,true);html+=rail('Em alta','O que está chamando atenção.',a.filter(x=>x.trending));html+=rail('Lançados recentemente','As novidades mais recentes da plataforma.',newest);[...new Set(a.map(x=>x.genre))].slice(0,5).forEach(g=>html+=rail(g,`Seleção em ${g.toLowerCase()}.`,a.filter(x=>x.genre===g)));$('homeContent').innerHTML=html}
function renderApp(){renderCategories();renderHero();renderWelcome();renderHome();updateNoticeCount();const adm=$('adminTopBtn');if(adm)adm.classList.toggle('hidden',!state.user?.admin)}
function scroll(id,d){const e=$(id);e?.scrollBy({left:d*e.clientWidth*.82,behavior:'smooth'})}
function close(){$('overlay').classList.add('hidden')}function closePlayer(){if(LX.stopMiniPlayer)LX.stopMiniPlayer(true);else{$('playerOverlay').classList.add('hidden');$('videoEl')?.pause()}}function closeReader(){$('readerOverlay').classList.add('hidden')}
function updateNoticeCount(){const c=D.notices().filter(x=>!x.read).length;$('notifyCount').textContent=c;$('notifyCount').style.display=c?'grid':'none'}
LX.ui={$, $$, state, esc, show, toast, initials, posterWalls, authTab, renderProfiles, renderApp, renderHome, renderCategories, items, close, closePlayer, closeReader, scroll, updateNoticeCount};
})();
