import 'dotenv/config';
import express from 'express';import helmet from 'helmet';import cors from 'cors';import cookieParser from 'cookie-parser';import rateLimit from 'express-rate-limit';import argon2 from 'argon2';import crypto from 'node:crypto';import pg from 'pg';import {z} from 'zod';
const {Pool}=pg;const app=express();const pool=new Pool({connectionString:process.env.DATABASE_URL});
app.use(helmet());app.use(cors({origin:process.env.WEB_ORIGIN,credentials:true}));app.use(cookieParser());app.use(express.json({limit:'1mb'}));app.use(rateLimit({windowMs:60_000,max:120,standardHeaders:true,legacyHeaders:false}));
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);const token=()=>crypto.randomBytes(32).toString('base64url');
app.get('/api/health',asyncRoute(async(req,res)=>{await pool.query('select 1');res.json({ok:true,service:'lxplus-api'})}));
app.post('/api/auth/register',asyncRoute(async(req,res)=>{const p=z.object({name:z.string().min(2).max(80),email:z.string().email(),password:z.string().min(8).max(128),ranking:z.boolean().default(true)}).parse(req.body);const hash=await argon2.hash(p.password);const q=await pool.query('insert into users(name,email,password_hash,ranking_visible) values($1,$2,$3,$4) returning id,name,email,ranking_visible',[p.name,p.email.toLowerCase(),hash,p.ranking]);res.status(201).json({user:q.rows[0]})}));
app.post('/api/auth/login',asyncRoute(async(req,res)=>{const p=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const q=await pool.query('select id,name,email,password_hash,role,ranking_visible from users where email=$1',[p.email.toLowerCase()]);const u=q.rows[0];if(!u||!await argon2.verify(u.password_hash,p.password))return res.status(401).json({error:'INVALID_CREDENTIALS'});const raw=token(),hash=crypto.createHash('sha256').update(raw).digest('hex');await pool.query("insert into sessions(user_id,token_hash,expires_at) values($1,$2,now()+interval '30 days')",[u.id,hash]);res.cookie('lx_session',raw,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:30*86400_000});delete u.password_hash;res.json({user:u})}));
async function auth(req,res,next){const raw=req.cookies?.lx_session||req.get('x-lx-session');if(!raw)return res.status(401).json({error:'UNAUTHENTICATED'});const h=crypto.createHash('sha256').update(raw).digest('hex');const q=await pool.query('select u.id,u.name,u.email,u.role from sessions s join users u on u.id=s.user_id where s.token_hash=$1 and s.expires_at>now()',[h]);if(!q.rows[0])return res.status(401).json({error:'INVALID_SESSION'});req.user=q.rows[0];next()}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'FORBIDDEN'});next()}
app.get('/api/catalog',asyncRoute(async(req,res)=>{const q=await pool.query("select * from content where status='published' order by created_at desc");res.json({items:q.rows})}));
app.get('/api/me',auth,asyncRoute(async(req,res)=>res.json({user:req.user})));
app.get('/api/me/preferences',auth,asyncRoute(async(req,res)=>{const q=await pool.query('select genres,autoplay,updated_at from user_preferences where user_id=$1',[req.user.id]);res.json({preferences:q.rows[0]||{genres:[],autoplay:true}})}));
app.put('/api/me/preferences',auth,asyncRoute(async(req,res)=>{const p=z.object({genres:z.array(z.string().max(80)).max(20).default([]),autoplay:z.boolean().default(true)}).parse(req.body);const q=await pool.query(`insert into user_preferences(user_id,genres,autoplay) values($1,$2,$3) on conflict(user_id) do update set genres=excluded.genres,autoplay=excluded.autoplay,updated_at=now() returning genres,autoplay,updated_at`,[req.user.id,p.genres,p.autoplay]);res.json({preferences:q.rows[0]})}));
app.get('/api/me/subscription',auth,asyncRoute(async(req,res)=>{const q=await pool.query(`select plan,status,current_period_end from subscriptions where user_id=$1 and status in ('active','trialing','past_due') order by updated_at desc limit 1`,[req.user.id]);res.json({subscription:q.rows[0]||null})}));
app.get('/api/admin/requests',auth,admin,asyncRoute(async(req,res)=>{const q=await pool.query('select * from requests order by votes desc,created_at desc');res.json({items:q.rows})}));
app.post('/api/requests',auth,asyncRoute(async(req,res)=>{const p=z.object({kind:z.enum(['Pedido','Problema']),mediaType:z.string().max(40),title:z.string().min(1).max(180),message:z.string().max(3000).default('')}).parse(req.body);const key=`${p.kind}|${p.mediaType}|${p.title}`.toLowerCase();const q=await pool.query(`insert into requests(user_id,kind,media_type,title,message,dedupe_key,votes,status) values($1,$2,$3,$4,$5,$6,1,'Novo') on conflict(dedupe_key) where status not in ('Concluído','Fechado') do update set votes=requests.votes+1,updated_at=now() returning *`,[req.user.id,p.kind,p.mediaType,p.title,p.message,key]);res.status(201).json(q.rows[0])}));
app.post('/api/analytics',auth,asyncRoute(async(req,res)=>{const p=z.object({event:z.string().max(80),data:z.record(z.any()).default({})}).parse(req.body);await pool.query('insert into analytics_events(user_id,event,data) values($1,$2,$3)',[req.user.id,p.event,p.data]);res.status(204).end()}));
app.post('/api/admin/media/sign',auth,admin,asyncRoute(async(req,res)=>{if(!process.env.MEDIA_UPLOAD_BASE)return res.status(503).json({error:'MEDIA_PROVIDER_NOT_CONFIGURED'});res.json({uploadBase:process.env.MEDIA_UPLOAD_BASE,note:'Replace with signed object-storage upload implementation.'})}));
app.use((err,req,res,next)=>{console.error(err);res.status(err?.name==='ZodError'?400:500).json({error:err?.name==='ZodError'?'INVALID_INPUT':'INTERNAL_ERROR'})});
const port=Number(process.env.PORT||8787);app.listen(port,()=>console.log(`LX Plus API on :${port}`));
