from pathlib import Path
p=Path('dist/lxplus-v27.js');s=p.read_text()
def swap(start,end,new):
 global s
 a=s.index(start);b=s.index(end,a);s=s[:a]+new+'\n'+s[b:]
swap('  function syncNowPlaying(){','  function normalizeQueueIndexes()', '''  function syncNowPlaying(){
    const panel=$('lxV27NowPlaying'),item=track();if(!panel||panel.classList.contains('hidden')||!item)return;
    const preview=isPreview(item),spotify=isSpotify(item),queue=state().musicQueue||[],current=Number(state().musicIndex)||0,upcoming=queue.slice(current+1,current+5);
    const signature=[item.mediaKey||item.remoteId||item.contentId||item.title,item.cover||'',item.artist||'',item.duration||'',current,queue.map(row=>row.mediaKey||row.remoteId||row.contentId||row.title).join(',')].join('|');
    if(panel.dataset.signature===signature){updateNowPlayingProgress();return}panel.dataset.signature=signature;panel.classList.toggle('no-queue',!upcoming.length);panel.style.setProperty('--now-art',LX.artwork.safeBackground(item));
    const icon=name=>LX.artwork.icon(name),button=(name,target,label)=>`<button type="button" onclick="${target}" aria-label="${label}" title="${label}">${icon(name)}</button>`;
    panel.innerHTML=`<div class="lx-v27-now-backdrop"></div><header>${button('down','LX.closeNowPlaying()','Fechar Tocando agora')}<div><span>TOCANDO AGORA</span><strong>${preview?'Prévia oficial':spotify?'Spotify oficial':'LX Music'}</strong></div>${button('queue','LX.openMusicQueue()','Abrir fila')}</header><main><section class="lx-v27-now-art">${LX.artwork.markup(item,{},'lx-now-art-image','Capa de '+(item.title||'música'))}<span class="${preview?'preview':''}">${preview?'PRÉVIA · TRECHO CURTO':spotify?'PLAYER OFICIAL SPOTIFY':'FAIXA COMPLETA'}</span></section><section class="lx-v27-now-copy"><div><span>${esc(item.album||'LX Music')}</span><h2>${esc(item.title||'Faixa')}</h2><p>${esc(item.artist||'LX Music')}</p></div>${button('heart',"document.getElementById('musicLikeBtn')?.click()",'Salvar na biblioteca')}<div class="lx-v27-now-progress"><input data-now-progress type="range" min="0" max="100" step="0.1" value="${Number($('musicProgress')?.value||0)}" aria-label="Posição da faixa" oninput="document.getElementById('musicProgress').value=this.value;document.getElementById('musicProgress').dispatchEvent(new Event('input'))"><div><span data-now-time>${esc($('musicTime')?.textContent||'0:00')}</span><span data-now-duration>${esc($('musicDuration')?.textContent||fmt(item.duration))}</span></div></div><div class="lx-v27-now-controls">${button('shuffle',"document.getElementById('musicShuffle')?.click()",'Embaralhar')}${button('prev',"document.getElementById('musicPrev')?.click()",'Anterior')}<button data-now-play type="button" class="main" aria-label="Reproduzir ou pausar" onclick="document.getElementById('musicPlay')?.click()">${icon(audio()?.paused?'play':'pause')}</button>${button('next',"document.getElementById('musicNext')?.click()",'Próxima')}${button('repeat',"document.getElementById('musicRepeat')?.click()",'Repetir')}</div><div class="lx-v27-now-actions">${button('lyrics','LX.openMusicLyrics?.()','Ver letra')}${button('queue','LX.openMusicQueue()','Abrir fila')}${spotify?`<button type="button" onclick="LX.closeNowPlaying();LX.openMusicProvider()" aria-label="Abrir Spotify oficial">${icon('external')} Spotify oficial</button>`:''}</div>${preview?'<div class="lx-v27-preview-warning"><strong>Isto é uma prévia.</strong><span>Para ouvir a faixa completa, abra o serviço oficial.</span></div>':''}</section>${upcoming.length?`<aside><span>PRÓXIMAS</span><h3>Na fila</h3>${upcoming.map((row,index)=>`<button type="button" onclick="LX.musicQueuePlay(${current+1+index})">${LX.artwork.markup(row,{},'lx-queue-art',row.title)}<span><strong>${esc(row.title)}</strong><small>${esc(row.artist)}</small></span></button>`).join('')}</aside>`:''}</main>`;
    LX.artwork.hydrate(panel);
  }
  function updateNowPlayingProgress(){const panel=$('lxV27NowPlaying'),source=$('musicProgress');if(!panel||panel.classList.contains('hidden'))return;const range=panel.querySelector('[data-now-progress]'),time=panel.querySelector('[data-now-time]'),duration=panel.querySelector('[data-now-duration]'),play=panel.querySelector('[data-now-play]');if(range&&source&&document.activeElement!==range)range.value=source.value||0;if(time)time.textContent=$('musicTime')?.textContent||'0:00';if(duration)duration.textContent=$('musicDuration')?.textContent||fmt(track()?.duration);if(play)play.innerHTML=LX.artwork.icon(audio()?.paused?'play':'pause')}
  document.addEventListener('lx:music-changed',()=>{const panel=$('lxV27NowPlaying');if(panel)panel.dataset.signature='';syncNowPlaying();setMusicKind()});document.addEventListener('lx:music-artwork-updated',()=>{const panel=$('lxV27NowPlaying');if(panel)panel.dataset.signature='';syncNowPlaying()});''')
s=s.replace('<img src="${esc(item.cover||\'\')}" alt="">',"${LX.artwork.markup(item,{},'lx-queue-art',item.title)}")
s=s.replace("  }\n  LX.openNowPlaying=openNowPlaying;", "    LX.artwork.hydrate(modal);\n  }\n  LX.openNowPlaying=openNowPlaying;")
s=s.replace("const copy=head.querySelector(':scope > div');if(copy&&!badge.isConnected)copy.appendChild(badge)","const copy=head.querySelector(':scope > div:nth-of-type(2)');if(copy&&badge.parentElement!==copy)copy.appendChild(badge)")
s=s.replace('<img src="${esc(imageOf(item))}" alt="" loading="lazy">',"${LX.artwork.markup({...item,cover:imageOf(item)}, {}, 'lx-spotify-art',item.name)}")
s=s.replace("  function spotifyCards(items,type){", "  function spotifyCards(items,type){")
s=s.replace("c.innerHTML=`<div class=\"lx-v27-spotify-results\"", "c.innerHTML=`<div class=\"lx-v27-spotify-results\"")
s=s.replace("</div>`;\n    }catch(error){c.innerHTML", "</div>`;LX.artwork.hydrate(c);\n    }catch(error){c.innerHTML")
s=s.replace("window.__LX_MODULES.v27='27.2'", "window.__LX_MODULES.v27='28.3'")
s=s.replace("LX.v27={version:'27.2'", "LX.v27={version:'28.3'")
p.write_text(s)
