from pathlib import Path
p=Path('dist/lxplus.js');s=p.read_text()
def swap(start,end,new):
 global s
 a=s.index(start);b=s.index(end,a);s=s[:a]+new+'\n'+s[b:]
s=s.replace("async function refreshCatalog(){const c=db();if(!c)return false;const {data,error}=await c.from('lx_catalog').select('id,payload,published,updated_at').order('updated_at',{ascending:false});if(error){if(!currentAuth)cache(S.keys.catalog,[]);return false}const mapped=mapCatalog(data||[]),sig=JSON.stringify((data||[]).map(r=>[String(r.id),r.updated_at,r.published]));const changed=sig!==catalogSig;catalogSig=sig;cache(S.keys.catalog,mapped);return changed||true}","async function refreshCatalog(){const c=db();if(!c){catalogLoadStatus='error';return false}catalogLoadStatus='loading';const {data,error}=await c.from('lx_catalog').select('id,payload,published,updated_at').order('updated_at',{ascending:false});if(error){catalogLoadStatus='error';return false}const mapped=mapCatalog(data||[]),sig=JSON.stringify((data||[]).map(r=>[String(r.id),r.updated_at,r.published]));catalogSig=sig;catalogLoadStatus='ready';cache(S.keys.catalog,mapped);return true}")
a=s.index('async function refreshCatalog(){');s=s[:a]+"let catalogLoadStatus='idle';\n"+s[a:]
s=s.replace('migrateLocalCatalog,status,hydrateUser,refreshBranding};','migrateLocalCatalog,status,hydrateUser,refreshBranding,catalogState:()=>catalogLoadStatus,retryCatalog:refreshCatalog};')
swap('function syncMusicSaveUI(){','function waitSpotifyAPI(','''function syncMusicSaveUI(){const t=currentMusic(),saved=!!t&&D.myList().some(x=>String(x)===String(t.contentId));[$('musicLikeBtn'),$('lxRightMusicLike'),...$$('[data-music-save-id]')].forEach(btn=>{if(!btn)return;const on=btn.dataset.musicSaveId?musicSaved(btn.dataset.musicSaveId):saved;btn.innerHTML=LX.artwork.icon('heart');btn.classList.toggle('active',on);btn.title=on?'Remover da biblioteca':'Salvar na biblioteca';btn.setAttribute('aria-label',btn.title);btn.setAttribute('aria-pressed',String(on))})}
function syncMusicCardState(){const t=currentMusic(),id=t?String(t.contentId):'',playing=!!t&&(!isSpotifyTrack(t)?!$('musicAudio')?.paused:spotifyPlayback.paused===false);$$('[data-music-id]').forEach(el=>{const on=String(el.dataset.musicId||'')===id;el.classList.toggle('is-current',on);el.classList.toggle('is-playing',on&&playing);const icon=el.matches('[data-music-play-icon]')?el:el.querySelector('[data-music-play-icon]');if(icon)icon.innerHTML=LX.artwork.icon(on&&playing?'pause':'play')});const now=$('lxMusicNow');if(now&&t){now.classList.remove('hidden');$('lxMusicNowTitle').textContent=t.title||'Música';$('lxMusicNowArtist').textContent=t.artist||'LX Music';LX.artwork.set($('lxMusicNowCover'),t,currentMusicContent()||{});$('lxMusicNowToggle').innerHTML=LX.artwork.icon(playing?'pause':'play')}else now?.classList.add('hidden');syncMusicSaveUI()}''')
swap('function resetMusicProvider(){','function musicToggleSaved(','''function resetMusicProvider(){const dock=$('musicDock'),panel=$('musicProviderPanel'),frame=$('musicProviderFrame'),host=$('spotifyEmbedHost'),toggle=$('musicProviderToggle');dock?.classList.remove('external-provider','provider-spotify','provider-youtube','provider-soundcloud','provider-drive','provider-open');panel?.classList.add('hidden');panel?.style.removeProperty('--provider-height');host?.classList.add('hidden');toggle?.classList.add('hidden');if(frame){frame.removeAttribute('src');frame.style.removeProperty('height');frame.removeAttribute('data-provider');frame.classList.add('hidden')}}
async function openMusicProvider(){const t=currentMusic(),source=LX.mediaSources?.describe?.(t?.mediaKey||'');if(!t||source?.kind!=='embed'||!source.src)return;const dock=$('musicDock'),panel=$('musicProviderPanel'),frame=$('musicProviderFrame'),host=$('spotifyEmbedHost'),height=Math.max(120,Math.min(270,+source.embedHeight||152));dock?.classList.add('provider-open');panel?.classList.remove('hidden');panel?.style.setProperty('--provider-height',height+'px');if(source.provider==='Spotify'&&source.spotifyUri){try{await ensureSpotifyController(source.spotifyUri,false);host?.classList.remove('hidden');frame?.classList.add('hidden');return}catch(error){console.warn('LX Spotify official embed',error)}}host?.classList.add('hidden');frame?.classList.remove('hidden');frame.style.height=height+'px';frame.src=source.src;frame.dataset.provider=source.provider||'';frame.title=`${source.provider||'Player oficial'} · ${t.title||'Música'}`;frame.setAttribute('allow','autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture')}
LX.openMusicProvider=openMusicProvider;''')
swap('function syncMusicMediaSession(','function music(id,', '''function syncMusicMediaSession(t=currentMusic()){if(!t||!('mediaSession'in navigator))return;try{if(window.MediaMetadata)navigator.mediaSession.metadata=new MediaMetadata({title:t.title||'Faixa',artist:t.artist||'LX Music',album:t.album||'LX Plus',artwork:[{src:LX.artwork.url(t,currentMusicContent()||{}),sizes:'512x512'}]});navigator.mediaSession.setActionHandler?.('play',toggleCurrentMusic);navigator.mediaSession.setActionHandler?.('pause',toggleCurrentMusic);navigator.mediaSession.setActionHandler?.('previoustrack',musicPrev);navigator.mediaSession.setActionHandler?.('nexttrack',()=>musicNext(true))}catch(e){console.warn('LX media session',e)}}''')
swap('function music(id,','function updateMusicUI(){', '''function music(id,index=0,autoplay=true){const x=D.catalog().find(i=>String(i.id)===String(id));if(!x)return;const tracks=x.tracks?.length?x.tracks:(x.mediaKey?[{number:1,title:x.title,duration:0,mediaKey:x.mediaKey}]:[]);if(!tracks.length){LX.toast('Esta música ainda não possui faixas reproduzíveis.');return}const nextIndex=Math.max(0,Math.min(index,tracks.length-1)),same=String(currentMusic()?.contentId)===String(id)&&state.musicIndex===nextIndex&&!$('musicDock')?.classList.contains('hidden');if(same){if(autoplay)toggleCurrentMusic();return}D.track('music',{id,title:x.title});rememberMusicStart(id,nextIndex);state.musicQueue=tracks.map((track,i)=>({...track,contentId:id,index:i,title:String(track.title||x.title||'Faixa').trim()||'Faixa',artist:String(track.artist||x.artist||'LX Music').trim()||'LX Music',cover:LX.artwork.url(track,x),album:x.title,albumCover:x.cover||'',contentCover:x.cover||''}));state.musicIndex=nextIndex;$('musicDock').classList.remove('hidden');loadTrack(autoplay)}
let musicLoadTicket=0;
async function loadTrack(autoplay=false){const t=currentMusic();if(!t)return;const ticket=++musicLoadTicket,a=$('musicAudio'),dock=$('musicDock'),label=$('musicProviderLabel'),toggle=$('musicProviderToggle'),content=currentMusicContent()||{},source=LX.mediaSources?.describe?.(t.mediaKey||'');a.pause();a.removeAttribute('src');if(musicObjectUrl?.startsWith?.('blob:'))try{URL.revokeObjectURL(musicObjectUrl)}catch{}musicObjectUrl=null;resetMusicProvider();$('musicTitle').textContent=t.title||'Faixa';$('musicArtist').textContent=t.artist||'LX Music';LX.artwork.set($('musicCover'),t,content);dock?.style.setProperty('--music-cover',LX.artwork.safeBackground(t,content));$('musicProgress').value=0;$('musicTime').textContent='0:00';$('musicDuration').textContent=LX.fmt(t.duration||0);$('musicProviderLabel').textContent=source?.provider||'LX Music';syncMusicMediaSession(t);syncMusicCardState();document.dispatchEvent(new CustomEvent('lx:music-changed',{detail:{item:t,index:state.musicIndex,provider:source?.provider||'LX Music'}}));LX.artwork.enrichSpotify?.(t);
 if(source?.kind==='embed'&&source.src){const provider=String(source.provider||''),cls=provider.toLowerCase().includes('spotify')?'provider-spotify':provider.toLowerCase().includes('youtube')?'provider-youtube':provider.toLowerCase().includes('soundcloud')?'provider-soundcloud':provider.toLowerCase().includes('drive')?'provider-drive':'';dock?.classList.add('external-provider');if(cls)dock?.classList.add(cls);toggle?.classList.remove('hidden');toggle.innerHTML=LX.artwork.icon('external');toggle.title=`Abrir ${provider} oficial`;toggle.setAttribute('aria-label',toggle.title);if(label)label.textContent=`${provider} oficial`;if(autoplay)await openMusicProvider();if(ticket!==musicLoadTicket)return;updateMusicUI();return}
 try{let src=null;if(t.mediaKey){const media=await S.getMedia(t.mediaKey);if(ticket!==musicLoadTicket)return;src=typeof media==='string'?media:media?URL.createObjectURL(media):null}else if(t.previewUrl)src=t.previewUrl;if(src){musicObjectUrl=src.startsWith?.('blob:')?src:null;a.src=src;a.load();if(autoplay)await a.play().catch(()=>{})}else if(autoplay)LX.toast('Não foi possível carregar esta faixa — tentar novamente.')}catch(error){console.warn('LX audio load',error);if(ticket===musicLoadTicket&&autoplay)LX.toast('Não foi possível carregar esta faixa — tentar novamente.')}if(ticket===musicLoadTicket)updateMusicUI()}''')
swap('function updateMusicUI(){','function musicNext(','''function updateMusicUI(){const a=$('musicAudio'),t=currentMusic(),sp=isSpotifyTrack(t),external=$('musicDock')?.classList.contains('external-provider'),paused=sp?spotifyPlayback.paused:a.paused;$('musicPlay').innerHTML=LX.artwork.icon(paused?'play':'pause');$('musicPlay').title=external?'Abrir ou controlar player oficial':'Reproduzir / pausar';$('musicPlay').setAttribute('aria-label',$('musicPlay').title);$('musicShuffle').classList.toggle('active',musicShuffleMode);$('musicShuffle').setAttribute('aria-pressed',String(musicShuffleMode));$('musicRepeat').classList.toggle('active',musicRepeatMode>0);$('musicRepeat').innerHTML=LX.artwork.icon('repeat')+(musicRepeatMode===2?'<sup>1</sup>':'');$('musicRepeat').setAttribute('aria-pressed',String(musicRepeatMode>0));try{if('mediaSession'in navigator)navigator.mediaSession.playbackState=t?(paused?'paused':'playing'):'none'}catch{}syncMusicCardState();syncMusicSaveUI();syncRightMusicRail?.()}''')
swap('function openMusicQueue(){','function saveMusicProgress(){', '''function openMusicQueue(){const queue=state.musicQueue||[];$('modal').innerHTML=`<button class="close-btn" onclick="LX.ui.close()">×</button><div class="panel-page lx-queue-page"><div class="panel-head"><div><span class="eyebrow">LX MUSIC</span><h2>Fila de reprodução</h2><p>${queue.length} ${queue.length===1?'faixa':'faixas'} na fila.</p></div></div>${queue.length?`<div class="lx-track-list">${queue.map((t,i)=>`<button class="${i===state.musicIndex?'active':''}" data-music-id="${esc(t.contentId)}" onclick="LX.musicQueuePlay(${i})">${LX.artwork.markup(t,{},'lx-queue-art',t.title)}<span><strong>${esc(t.title)}</strong><small>${esc(t.artist)}</small></span><em>${LX.fmt(t.duration||0)}</em><i data-music-play-icon>${LX.artwork.icon('play')}</i></button>`).join('')}</div>`:musicEmpty('Sua fila está vazia','Escolha uma música para começar.')}</div>`;$('overlay').classList.remove('hidden');LX.artwork.hydrate($('modal'));queueMicrotask(syncMusicCardState)}''')
s=s.replace("if(sp&&spotifyController){try{spotifyController.togglePlay?.()}catch{};return}const a=$('musicAudio');","if(sp){if(spotifyController){try{spotifyController.togglePlay?.()}catch{};return}openMusicProvider();return}const a=$('musicAudio');")
s=s.replace("if($('musicDock')?.classList.contains('external-provider')){const dock=$('musicDock');dock?.classList.toggle('provider-open');return}","if($('musicDock')?.classList.contains('external-provider')){LX.openMusicProvider();return}")
s=s.replace("$('musicProviderToggle')&&($('musicProviderToggle').onclick=()=>{$('musicDock')?.classList.toggle('provider-open')});","$('musicProviderToggle')&&($('musicProviderToggle').onclick=()=>LX.openMusicProvider());")
s=s.replace("spotifyPlayback.paused=true;syncMusicCardState()};", "spotifyPlayback.paused=true;syncMusicCardState();document.dispatchEvent(new Event('lx:music-closed'))};")
s=s.replace("$('musicLikeBtn')&&($('musicLikeBtn').onclick=musicToggleSavedCurrent);", "document.addEventListener('lx:music-artwork-updated',event=>{if(currentMusic()!==event.detail?.item)return;const t=event.detail.item;LX.artwork.set($('musicCover'),t,currentMusicContent()||{});$('musicTitle').textContent=t.title||'Faixa';$('musicArtist').textContent=t.artist||'LX Music';$('musicDuration').textContent=LX.fmt(t.duration||0);syncMusicMediaSession(t);syncMusicCardState();document.dispatchEvent(new Event('lx:music-changed'))});$('musicLikeBtn')&&($('musicLikeBtn').onclick=musicToggleSavedCurrent);")
p.write_text(s)
